In [1]:
import pandas as pd
import numpy as np

In [2]:
seoul = pd.read_csv("C:/data/now_used/1015_data3.csv")

In [3]:
seoul

,건축물대장코드,구시군,읍면동,번,지,입주일,상가유형,지하총층,지상총층,연면적m2,...,주변세대수점수,주변평당가점수,상권코드명,평균월매출금액,평균월매출건수,평균주중매출금액,평균주말매출금액,편의점임대료,공시지가,행정동생활인구
0,11110-10014,종로구,동숭동,1,114,1982-12-24,근린상가,1,5,1563.66,...,1.176,10.477,이화장길,1276469803,92138,926358383,350111420,131091.221409,22840000,38293.0
1,11110-100180009,종로구,동숭동,1,67,2008-07-03,기타상가,4,5,8585.08,...,1.207,10.754,이화장길,1276469803,92138,926358383,350111420,66131.584897,16310000,38293.0
2,11110-100184402,종로구,관훈동,186,0,2008-12-29,근린상가,0,3,172.11,...,0.363,19.104,계동길,725431028,41102,530637184,194793844,101021.253105,24600000,86083.0
3,11110-100190514,종로구,누하동,245,6,2011-09-28,근린상가,0,4,233.03,...,1.979,16.353,자하문로7길,1266093633,59989,952608422,313485211,67634.444078,7727000,40687.0
4,11110-100190842,종로구,효제동,19,3,2011-10-14,근린상가,0,5,253.80,...,0.810,10.063,율곡로16길,701283928,59235,586470792,114813136,112721.417069,4878000,30695.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9257,11740-9659,강동구,고덕동,645,4,1988-09-16,근린상가,1,4,493.71,...,18.968,40.630,고덕로61길,237774734,14458,184722166,53052568,157349.896480,5684000,50099.0
9258,11740-9676,강동구,명일동,312,42,1980-06-27,근린상가,1,3,988.04,...,12.853,39.510,상암로51길,1138515459,61110,811089104,327426355,37556.499110,12580000,59355.0
9259,11740-9698,강동구,명일동,326,11,1981-10-05,근린상가,1,2,741.99,...,10.374,109.826,상암로51길,1138515459,61110,811089104,327426355,37556.499110,6444000,59355.0
9260,11740-9843,강동구,둔촌동,609,3,1993-12-06,근린상가,1,4,659.00,...,7.339,47.818,명일로13길,731403749,43065,546770943,184632806,39411.064842,6762000,55551.0
9261,11740-9917,강동구,길동,413,1,2002-02-06,기타상가,4,10,20582.74,...,2.255,43.087,진황도로47길,1534886060,80643,1128660267,406225793,156815.440290,6416000,55551.0

In [4]:
seoul.columns

Index(['건축물대장코드', '구시군', '읍면동', '번', '지', '입주일', '상가유형', '지하총층', '지상총층',
       '연면적m2', '주차대수', '승강기수', '경도', '위도', 'usage_area', 'cont_area', 'RENT',
       'rent_ua', 'rent_ca', 'floor', '전철역명', '지하철거리m', '승객수점수', '건물별전기사용량',
       '본번별평균사용량', '횡단보도거리m', '건물연차', '가까운아파트', '가까운아파트총세대수', '가까운아파트평균평당가',
       '아파트거리', '주변세대수점수', '주변평당가점수', '상권코드명', '평균월매출금액', '평균월매출건수',
       '평균주중매출금액', '평균주말매출금액', '편의점임대료', '공시지가', '행정동생활인구'],
      dtype='object')

In [5]:
seoul_ua = seoul[['rent_ua', '지하총층', '지상총층',
       '연면적m2', '주차대수', '승강기수', 'usage_area', 'cont_area',
       '지하철거리m', '승객수점수', '건물별전기사용량',
       '본번별평균사용량', '횡단보도거리m', '건물연차', '가까운아파트총세대수', '가까운아파트평균평당가',
       '아파트거리', '주변세대수점수', '주변평당가점수', '평균월매출금액', '평균월매출건수',
       '평균주중매출금액', '평균주말매출금액', '편의점임대료', '공시지가', '행정동생활인구']]
seoul_ua.head()

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,아파트거리,주변세대수점수,주변평당가점수,평균월매출금액,평균월매출건수,평균주중매출금액,평균주말매출금액,편의점임대료,공시지가,행정동생활인구
0,48.387097,1,5,1563.66,0,1,15.50,15.50,1.082077,71533.898,...,519.940374,1.176,10.477,1276469803,92138,926358383,350111420,131091.221409,22840000,38293.0
1,13.155340,4,5,8585.08,7,4,103.00,143.92,1.373136,117064.164,...,497.856179,1.207,10.754,1276469803,92138,926358383,350111420,66131.584897,16310000,38293.0
2,11.891892,0,3,172.11,0,1,185.00,200.00,2.508637,46623.003,...,249.441747,0.363,19.104,725431028,41102,530637184,194793844,101021.253105,24600000,86083.0
3,3.778770,0,4,233.03,2,0,58.22,58.22,4.791703,29040.490,...,426.832578,1.979,16.353,1266093633,59989,952608422,313485211,67634.444078,7727000,40687.0
4,2.037351,0,5,253.80,0,0,58.90,66.20,3.818611,34219.916,...,491.694446,0.810,10.063,701283928,59235,586470792,114813136,112721.417069,4878000,30695.0

In [6]:
# 주차가능여부, 승강기여부 변수 추가
lst = []
[lst.append(1) if i > 0 else lst.append(0) for i in seoul_ua['주차대수']]

seoul_ua['주차가능여부'] = lst

lst = []
[lst.append(1) if i > 0 else lst.append(0) for i in seoul_ua['승강기수']]

seoul_ua['승강기여부'] = lst

seoul_ua

<ipython-input-6-f653761b9a8a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua['주차가능여부'] = lst
<ipython-input-6-f653761b9a8a>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua['승강기여부'] = lst

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,주변평당가점수,평균월매출금액,평균월매출건수,평균주중매출금액,평균주말매출금액,편의점임대료,공시지가,행정동생활인구,주차가능여부,승강기여부
0,48.387097,1,5,1563.66,0,1,15.50,15.50,1.082077,71533.898,...,10.477,1276469803,92138,926358383,350111420,131091.221409,22840000,38293.0,0,1
1,13.155340,4,5,8585.08,7,4,103.00,143.92,1.373136,117064.164,...,10.754,1276469803,92138,926358383,350111420,66131.584897,16310000,38293.0,1,1
2,11.891892,0,3,172.11,0,1,185.00,200.00,2.508637,46623.003,...,19.104,725431028,41102,530637184,194793844,101021.253105,24600000,86083.0,0,1
3,3.778770,0,4,233.03,2,0,58.22,58.22,4.791703,29040.490,...,16.353,1266093633,59989,952608422,313485211,67634.444078,7727000,40687.0,1,0
4,2.037351,0,5,253.80,0,0,58.90,66.20,3.818611,34219.916,...,10.063,701283928,59235,586470792,114813136,112721.417069,4878000,30695.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9257,2.156190,1,4,493.71,3,0,783.79,891.83,4.357042,8921.374,...,40.630,237774734,14458,184722166,53052568,157349.896480,5684000,50099.0,1,0
9258,10.439427,1,3,988.04,0,0,41.19,41.19,0.729846,33569.452,...,39.510,1138515459,61110,811089104,327426355,37556.499110,12580000,59355.0,0,0
9259,3.761755,1,2,741.99,4,0,127.60,127.60,2.046134,16942.142,...,109.826,1138515459,61110,811089104,327426355,37556.499110,6444000,59355.0,1,0
9260,4.672416,1,4,659.00,5,0,291.07,321.87,6.165909,22247.037,...,47.818,731403749,43065,546770943,184632806,39411.064842,6762000,55551.0,1,0
9261,3.905050,4,10,20582.74,149,2,227.91,300.00,1.656423,90212.844,...,43.087,1534886060,80643,1128660267,406225793,156815.440290,6416000,55551.0,1,1

In [7]:
# 0값 제거
seoul_ua1 = seoul_ua.copy()

seoul_ua1 = seoul_ua1[seoul_ua1.rent_ua != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.지상총층 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.연면적m2 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.usage_area != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.cont_area != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.지하철거리m != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.승객수점수 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.건물별전기사용량 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.본번별평균사용량 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.횡단보도거리m != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.가까운아파트총세대수 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.가까운아파트평균평당가 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.아파트거리 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.주변세대수점수 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.주변평당가점수 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.평균월매출금액 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.평균월매출건수 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.평균주중매출금액 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.평균주말매출금액 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.공시지가 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.행정동생활인구 != 0]
seoul_ua1

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,주변평당가점수,평균월매출금액,평균월매출건수,평균주중매출금액,평균주말매출금액,편의점임대료,공시지가,행정동생활인구,주차가능여부,승강기여부
0,48.387097,1,5,1563.66,0,1,15.50,15.50,1.082077,71533.898,...,10.477,1276469803,92138,926358383,350111420,131091.221409,22840000,38293.0,0,1
1,13.155340,4,5,8585.08,7,4,103.00,143.92,1.373136,117064.164,...,10.754,1276469803,92138,926358383,350111420,66131.584897,16310000,38293.0,1,1
2,11.891892,0,3,172.11,0,1,185.00,200.00,2.508637,46623.003,...,19.104,725431028,41102,530637184,194793844,101021.253105,24600000,86083.0,0,1
3,3.778770,0,4,233.03,2,0,58.22,58.22,4.791703,29040.490,...,16.353,1266093633,59989,952608422,313485211,67634.444078,7727000,40687.0,1,0
4,2.037351,0,5,253.80,0,0,58.90,66.20,3.818611,34219.916,...,10.063,701283928,59235,586470792,114813136,112721.417069,4878000,30695.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9257,2.156190,1,4,493.71,3,0,783.79,891.83,4.357042,8921.374,...,40.630,237774734,14458,184722166,53052568,157349.896480,5684000,50099.0,1,0
9258,10.439427,1,3,988.04,0,0,41.19,41.19,0.729846,33569.452,...,39.510,1138515459,61110,811089104,327426355,37556.499110,12580000,59355.0,0,0
9259,3.761755,1,2,741.99,4,0,127.60,127.60,2.046134,16942.142,...,109.826,1138515459,61110,811089104,327426355,37556.499110,6444000,59355.0,1,0
9260,4.672416,1,4,659.00,5,0,291.07,321.87,6.165909,22247.037,...,47.818,731403749,43065,546770943,184632806,39411.064842,6762000,55551.0,1,0
9261,3.905050,4,10,20582.74,149,2,227.91,300.00,1.656423,90212.844,...,43.087,1534886060,80643,1128660267,406225793,156815.440290,6416000,55551.0,1,1

In [8]:
# 이상값 제거
# 일반적으로는 iqt = 1.5 * (q3 - q1)로 정의. 하지만 너무 많은 데이터가 이상치로 빠지는 것을 막기 위해 iqt = 1.8 * (q3 - q1)로 정의하였다.

seoul_ua2 = seoul_ua1.copy()

q1 = seoul_ua2["rent_ua"].quantile(0.25)
q3 = seoul_ua2["rent_ua"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["rent_ua"][(seoul_ua2["rent_ua"] > (q3 + iqt)) | (seoul_ua2["rent_ua"] < (q1 - iqt))] = None

q1 = seoul_ua2["연면적m2"].quantile(0.25)
q3 = seoul_ua2["연면적m2"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["연면적m2"][(seoul_ua2["연면적m2"] > (q3 + iqt)) | (seoul_ua2["연면적m2"] < (q1 - iqt))] = None

q1 = seoul_ua2["usage_area"].quantile(0.25)
q3 = seoul_ua2["usage_area"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["usage_area"][(seoul_ua2["usage_area"] > (q3 + iqt)) | (seoul_ua2["usage_area"] < (q1 - iqt))] = None

q1 = seoul_ua2["cont_area"].quantile(0.25)
q3 = seoul_ua2["cont_area"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["cont_area"][(seoul_ua2["cont_area"] > (q3 + iqt)) | (seoul_ua2["cont_area"] < (q1 - iqt))] = None

q1 = seoul_ua2["지하철거리m"].quantile(0.25)
q3 = seoul_ua2["지하철거리m"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["지하철거리m"][(seoul_ua2["지하철거리m"] > (q3 + iqt)) | (seoul_ua2["지하철거리m"] < (q1 - iqt))] = None

q1 = seoul_ua2["승객수점수"].quantile(0.25)
q3 = seoul_ua2["승객수점수"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["승객수점수"][(seoul_ua2["승객수점수"] > (q3 + iqt)) | (seoul_ua2["승객수점수"] < (q1 - iqt))] = None

q1 = seoul_ua2["건물별전기사용량"].quantile(0.25)
q3 = seoul_ua2["건물별전기사용량"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["건물별전기사용량"][(seoul_ua2["건물별전기사용량"] > (q3 + iqt)) | (seoul_ua2["건물별전기사용량"] < (q1 - iqt))] = None

q1 = seoul_ua2["본번별평균사용량"].quantile(0.25)
q3 = seoul_ua2["본번별평균사용량"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["본번별평균사용량"][(seoul_ua2["본번별평균사용량"] > (q3 + iqt)) | (seoul_ua2["본번별평균사용량"] < (q1 - iqt))] = None

q1 = seoul_ua2["횡단보도거리m"].quantile(0.25)
q3 = seoul_ua2["횡단보도거리m"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["횡단보도거리m"][(seoul_ua2["횡단보도거리m"] > (q3 + iqt)) | (seoul_ua2["횡단보도거리m"] < (q1 - iqt))] = None

q1 = seoul_ua2["가까운아파트총세대수"].quantile(0.25)
q3 = seoul_ua2["가까운아파트총세대수"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["가까운아파트총세대수"][(seoul_ua2["가까운아파트총세대수"] > (q3 + iqt)) | (seoul_ua2["가까운아파트총세대수"] < (q1 - iqt))] = None

q1 = seoul_ua2["가까운아파트평균평당가"].quantile(0.25)
q3 = seoul_ua2["가까운아파트평균평당가"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["가까운아파트평균평당가"][(seoul_ua2["가까운아파트평균평당가"] > (q3 + iqt)) | (seoul_ua2["가까운아파트평균평당가"] < (q1 - iqt))] = None

q1 = seoul_ua2["아파트거리"].quantile(0.25)
q3 = seoul_ua2["아파트거리"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["아파트거리"][(seoul_ua2["아파트거리"] > (q3 + iqt)) | (seoul_ua2["아파트거리"] < (q1 - iqt))] = None

q1 = seoul_ua2["주변세대수점수"].quantile(0.25)
q3 = seoul_ua2["주변세대수점수"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["주변세대수점수"][(seoul_ua2["주변세대수점수"] > (q3 + iqt)) | (seoul_ua2["주변세대수점수"] < (q1 - iqt))] = None

q1 = seoul_ua2["주변평당가점수"].quantile(0.25)
q3 = seoul_ua2["주변평당가점수"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["주변평당가점수"][(seoul_ua2["주변평당가점수"] > (q3 + iqt)) | (seoul_ua2["주변평당가점수"] < (q1 - iqt))] = None

q1 = seoul_ua2["평균월매출금액"].quantile(0.25)
q3 = seoul_ua2["평균월매출금액"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["평균월매출금액"][(seoul_ua2["평균월매출금액"] > (q3 + iqt)) | (seoul_ua2["평균월매출금액"] < (q1 - iqt))] = None

q1 = seoul_ua2["평균월매출건수"].quantile(0.25)
q3 = seoul_ua2["평균월매출건수"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["평균월매출건수"][(seoul_ua2["평균월매출건수"] > (q3 + iqt)) | (seoul_ua2["평균월매출건수"] < (q1 - iqt))] = None

q1 = seoul_ua2["평균주중매출금액"].quantile(0.25)
q3 = seoul_ua2["평균주중매출금액"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["평균주중매출금액"][(seoul_ua2["평균주중매출금액"] > (q3 + iqt)) | (seoul_ua2["평균주중매출금액"] < (q1 - iqt))] = None

q1 = seoul_ua2["평균주말매출금액"].quantile(0.25)
q3 = seoul_ua2["평균주말매출금액"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["평균주말매출금액"][(seoul_ua2["평균주말매출금액"] > (q3 + iqt)) | (seoul_ua2["평균주말매출금액"] < (q1 - iqt))] = None

q1 = seoul_ua2["편의점임대료"].quantile(0.25)
q3 = seoul_ua2["편의점임대료"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["편의점임대료"][(seoul_ua2["편의점임대료"] > (q3 + iqt)) | (seoul_ua2["편의점임대료"] < (q1 - iqt))] = None

q1 = seoul_ua2["공시지가"].quantile(0.25)
q3 = seoul_ua2["공시지가"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["공시지가"][(seoul_ua2["공시지가"] > (q3 + iqt)) | (seoul_ua2["공시지가"] < (q1 - iqt))] = None

q1 = seoul_ua2["행정동생활인구"].quantile(0.25)
q3 = seoul_ua2["행정동생활인구"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["행정동생활인구"][(seoul_ua2["행정동생활인구"] > (q3 + iqt)) | (seoul_ua2["행정동생활인구"] < (q1 - iqt))] = None


seoul_ua2 = seoul_ua2.dropna(axis = 0, how= 'any') # NaN값 제거를 변수 한 개의 이상값을 제거할 때마다 해주면 더 많은 데이터가 삭제되기 때문에 이상값 제거를 모두 마친 후 마지막에 한 번에 제거.

seoul_ua2

<ipython-input-8-d668468f1f8f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["rent_ua"][(seoul_ua2["rent_ua"] > (q3 + iqt)) | (seoul_ua2["rent_ua"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["연면적m2"][(seoul_ua2["연면적m2"] > (q3 + iqt)) | (seoul_ua2["연면적m2"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["usage_area"][(seoul_ua2["usage_area"] > (q3 + iqt)) | (seoul_ua2["usage_area"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["cont_area"][(seoul_ua2["cont_area"] > (q3 + iqt)) | (seoul_ua2["cont_area"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["지하철거리m"][(seoul_ua2["지하철거리m"] > (q3 + iqt)) | (seoul_ua2["지하철거리m"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["승객수점수"][(seoul_ua2["승객수점수"] > (q3 + iqt)) | (seoul_ua2["승객수점수"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["건물별전기사용량"][(seoul_ua2["건물별전기사용량"] > (q3 + iqt)) | (seoul_ua2["건물별전기사용량"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["본번별평균사용량"][(seoul_ua2["본번별평균사용량"] > (q3 + iqt)) | (seoul_ua2["본번별평균사용량"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["횡단보도거리m"][(seoul_ua2["횡단보도거리m"] > (q3 + iqt)) | (seoul_ua2["횡단보도거리m"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["가까운아파트총세대수"][(seoul_ua2["가까운아파트총세대수"] > (q3 + iqt)) | (seoul_ua2["가까운아파트총세대수"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["가까운아파트평균평당가"][(seoul_ua2["가까운아파트평균평당가"] > (q3 + iqt)) | (seoul_ua2["가까운아파트평균평당가"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["아파트거리"][(seoul_ua2["아파트거리"] > (q3 + iqt)) | (seoul_ua2["아파트거리"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["주변세대수점수"][(seoul_ua2["주변세대수점수"] > (q3 + iqt)) | (seoul_ua2["주변세대수점수"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["주변평당가점수"][(seoul_ua2["주변평당가점수"] > (q3 + iqt)) | (seoul_ua2["주변평당가점수"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["평균월매출금액"][(seoul_ua2["평균월매출금액"] > (q3 + iqt)) | (seoul_ua2["평균월매출금액"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["평균월매출건수"][(seoul_ua2["평균월매출건수"] > (q3 + iqt)) | (seoul_ua2["평균월매출건수"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["평균주중매출금액"][(seoul_ua2["평균주중매출금액"] > (q3 + iqt)) | (seoul_ua2["평균주중매출금액"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:94: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["평균주말매출금액"][(seoul_ua2["평균주말매출금액"] > (q3 + iqt)) | (seoul_ua2["평균주말매출금액"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["편의점임대료"][(seoul_ua2["편의점임대료"] > (q3 + iqt)) | (seoul_ua2["편의점임대료"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["공시지가"][(seoul_ua2["공시지가"] > (q3 + iqt)) | (seoul_ua2["공시지가"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["행정동생활인구"][(seoul_ua2["행정동생활인구"] > (q3 + iqt)) | (seoul_ua2["행정동생활인구"] < (q1 - iqt))] = None

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,주변평당가점수,평균월매출금액,평균월매출건수,평균주중매출금액,평균주말매출금액,편의점임대료,공시지가,행정동생활인구,주차가능여부,승강기여부
3,3.778770,0,4,233.03,2,0,58.22,58.22,4.791703,29040.490,...,16.353,1.266094e+09,59989.0,952608422.0,313485211.0,67634.444078,7727000.0,40687.0,1,0
4,2.037351,0,5,253.80,0,0,58.90,66.20,3.818611,34219.916,...,10.063,7.012839e+08,59235.0,586470792.0,114813136.0,112721.417069,4878000.0,30695.0,0,0
9,4.792551,1,4,458.95,0,0,73.03,73.03,3.944218,24836.371,...,14.742,1.132740e+09,82393.0,810808853.0,321931432.0,95483.870968,8977000.0,55931.0,0,0
15,2.249335,1,3,480.67,0,0,146.71,146.71,3.241511,60826.450,...,7.496,1.276470e+09,92138.0,926358383.0,350111420.0,85005.100306,6848000.0,38293.0,0,0
17,5.451242,1,4,503.46,3,0,99.06,127.74,3.672770,18686.432,...,14.908,1.266094e+09,59989.0,952608422.0,313485211.0,90696.313634,9104000.0,29924.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9247,2.861953,0,5,675.70,5,0,59.40,66.40,4.533248,16690.231,...,52.278,1.194210e+09,67939.0,923563626.0,270646039.0,79175.105874,5443000.0,52160.0,1,0
9248,3.083906,1,3,410.52,2,0,85.93,239.03,7.958086,10810.675,...,25.011,5.051960e+08,29735.0,366639062.0,138556963.0,43392.132818,6388000.0,67018.0,1,0
9249,2.352941,1,3,662.36,4,0,59.50,82.64,2.570816,30563.172,...,43.535,9.012489e+08,48800.0,633431615.0,267817266.0,35753.147831,5623000.0,105763.0,1,0
9251,3.064516,1,5,663.60,5,0,62.00,76.60,1.902117,36497.040,...,32.865,9.012489e+08,48800.0,633431615.0,267817266.0,35753.147831,4391000.0,105763.0,1,0
9260,4.672416,1,4,659.00,5,0,291.07,321.87,6.165909,22247.037,...,47.818,7.314037e+08,43065.0,546770943.0,184632806.0,39411.064842,6762000.0,55551.0,1,0

In [9]:
seoul_ua2_log = seoul_ua2.copy()
seoul_ua2_log

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,주변평당가점수,평균월매출금액,평균월매출건수,평균주중매출금액,평균주말매출금액,편의점임대료,공시지가,행정동생활인구,주차가능여부,승강기여부
3,3.778770,0,4,233.03,2,0,58.22,58.22,4.791703,29040.490,...,16.353,1.266094e+09,59989.0,952608422.0,313485211.0,67634.444078,7727000.0,40687.0,1,0
4,2.037351,0,5,253.80,0,0,58.90,66.20,3.818611,34219.916,...,10.063,7.012839e+08,59235.0,586470792.0,114813136.0,112721.417069,4878000.0,30695.0,0,0
9,4.792551,1,4,458.95,0,0,73.03,73.03,3.944218,24836.371,...,14.742,1.132740e+09,82393.0,810808853.0,321931432.0,95483.870968,8977000.0,55931.0,0,0
15,2.249335,1,3,480.67,0,0,146.71,146.71,3.241511,60826.450,...,7.496,1.276470e+09,92138.0,926358383.0,350111420.0,85005.100306,6848000.0,38293.0,0,0
17,5.451242,1,4,503.46,3,0,99.06,127.74,3.672770,18686.432,...,14.908,1.266094e+09,59989.0,952608422.0,313485211.0,90696.313634,9104000.0,29924.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9247,2.861953,0,5,675.70,5,0,59.40,66.40,4.533248,16690.231,...,52.278,1.194210e+09,67939.0,923563626.0,270646039.0,79175.105874,5443000.0,52160.0,1,0
9248,3.083906,1,3,410.52,2,0,85.93,239.03,7.958086,10810.675,...,25.011,5.051960e+08,29735.0,366639062.0,138556963.0,43392.132818,6388000.0,67018.0,1,0
9249,2.352941,1,3,662.36,4,0,59.50,82.64,2.570816,30563.172,...,43.535,9.012489e+08,48800.0,633431615.0,267817266.0,35753.147831,5623000.0,105763.0,1,0
9251,3.064516,1,5,663.60,5,0,62.00,76.60,1.902117,36497.040,...,32.865,9.012489e+08,48800.0,633431615.0,267817266.0,35753.147831,4391000.0,105763.0,1,0
9260,4.672416,1,4,659.00,5,0,291.07,321.87,6.165909,22247.037,...,47.818,7.314037e+08,43065.0,546770943.0,184632806.0,39411.064842,6762000.0,55551.0,1,0

In [10]:
# 요약 통계량 확인하기

seoul_ua2_log = seoul_ua2_log[seoul_ua2_log['연면적m2'] != 0]
seoul_ua2_log.describe()

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,주변평당가점수,평균월매출금액,평균월매출건수,평균주중매출금액,평균주말매출금액,편의점임대료,공시지가,행정동생활인구,주차가능여부,승강기여부
count,4474.000000,4474.000000,4474.000000,4474.000000,4474.000000,4474.000000,4474.000000,4474.000000,4474.000000,4474.000000,...,4474.000000,4.474000e+03,4474.000000,4.474000e+03,4.474000e+03,4474.000000,4.474000e+03,4474.000000,4474.000000,4474.000000
mean,3.879297,0.863880,3.797273,662.414389,2.402325,0.138355,158.757300,181.684799,4.370455,46063.046057,...,27.895469,1.088481e+09,58093.952168,7.920690e+08,2.964118e+08,60532.869536,6.402881e+06,54904.991283,0.510729,0.136790
std,1.783621,0.415469,1.409235,488.009323,3.300029,0.351725,142.925113,164.783598,2.323820,33471.993796,...,16.779590,4.380602e+08,23018.818752,3.156274e+08,1.380142e+08,34174.628736,2.842300e+06,23590.646315,0.499941,0.343664
min,0.297063,0.000000,1.000000,12.030000,0.000000,0.000000,6.000000,8.000000,0.183268,3073.198000,...,4.556000,1.119613e+08,6561.000000,8.237247e+07,2.958881e+07,3156.167151,6.760000e+04,9970.000000,0.000000,0.000000
25%,2.597403,1.000000,3.000000,316.035000,0.000000,0.000000,56.000000,63.772500,2.570710,21323.118250,...,15.681250,7.394747e+08,41405.000000,5.561323e+08,1.904996e+08,35753.147831,4.350000e+06,38287.000000,0.000000,0.000000
50%,3.493797,1.000000,4.000000,539.360000,1.000000,0.000000,105.805000,122.380000,4.053790,36101.665000,...,23.263000,1.077646e+09,56100.000000,7.819209e+08,2.764897e+08,50639.321433,5.662000e+06,50219.000000,1.000000,0.000000
75%,4.786422,1.000000,5.000000,871.320000,4.000000,0.000000,208.882500,241.665000,5.759044,61522.920500,...,36.439750,1.384609e+09,72469.000000,1.023801e+09,3.707628e+08,77808.670702,7.756000e+06,68663.000000,1.000000,0.000000
max,10.892587,3.000000,11.000000,2823.450000,69.000000,4.000000,720.740000,874.300000,11.744879,179012.864000,...,87.925000,2.137533e+09,142885.000000,1.620105e+09,8.670086e+08,189181.200118,1.900000e+07,124552.000000,1.000000,1.000000

In [11]:
seoul_ua2_log.columns

Index(['rent_ua', '지하총층', '지상총층', '연면적m2', '주차대수', '승강기수', 'usage_area',
       'cont_area', '지하철거리m', '승객수점수', '건물별전기사용량', '본번별평균사용량', '횡단보도거리m',
       '건물연차', '가까운아파트총세대수', '가까운아파트평균평당가', '아파트거리', '주변세대수점수', '주변평당가점수',
       '평균월매출금액', '평균월매출건수', '평균주중매출금액', '평균주말매출금액', '편의점임대료', '공시지가',
       '행정동생활인구', '주차가능여부', '승강기여부'],
      dtype='object')

In [12]:
columns = ['rent_ua', '연면적m2', 'usage_area',
       'cont_area', '지하철거리m', '승객수점수', '건물별전기사용량', '본번별평균사용량', '횡단보도거리m',
       '건물연차', '가까운아파트총세대수', '가까운아파트평균평당가', '아파트거리', '주변세대수점수', '주변평당가점수',
       '평균월매출금액', '평균월매출건수', '평균주중매출금액', '평균주말매출금액', '편의점임대료', '공시지가',
       '행정동생활인구']

In [13]:
# columns에 담긴 변수 log

import math

for i in columns:
    seoul_ua2_log['{}_log'.format(i)] = np.log(seoul_ua2_log['{}'.format(i)])
    
seoul_ua2_log

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,아파트거리_log,주변세대수점수_log,주변평당가점수_log,평균월매출금액_log,평균월매출건수_log,평균주중매출금액_log,평균주말매출금액_log,편의점임대료_log,공시지가_log,행정동생활인구_log
3,3.778770,0,4,233.03,2,0,58.22,58.22,4.791703,29040.490,...,6.056392,0.682592,2.794411,20.959202,11.001916,20.674714,19.563263,11.121873,15.860231,10.613664
4,2.037351,0,5,253.80,0,0,58.90,66.20,3.818611,34219.916,...,6.197857,-0.210721,2.308865,20.368423,10.989268,20.189633,18.558816,11.632675,15.400246,10.331855
9,4.792551,1,4,458.95,0,0,73.03,73.03,3.944218,24836.371,...,6.048070,0.506818,2.690701,20.847906,11.319256,20.513543,19.589849,11.466713,16.010176,10.931874
15,2.249335,1,3,480.67,0,0,146.71,146.71,3.241511,60826.450,...,6.551802,0.552735,2.014370,20.967364,11.431043,20.646772,19.673762,11.350467,15.739467,10.553022
17,5.451242,1,4,503.46,3,0,99.06,127.74,3.672770,18686.432,...,6.336291,0.417394,2.701898,20.959202,11.001916,20.674714,19.563263,11.415272,16.024224,10.306416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9247,2.861953,0,5,675.70,5,0,59.40,66.40,4.533248,16690.231,...,3.741044,0.750472,3.956576,20.900750,11.126366,20.643750,19.416322,11.279417,15.509841,10.862071
9248,3.083906,1,3,410.52,2,0,85.93,239.03,7.958086,10810.675,...,5.402668,1.080109,3.219316,20.040457,10.300080,19.719888,18.746792,10.678033,15.669932,11.112717
9249,2.352941,1,3,662.36,4,0,59.50,82.64,2.570816,30563.172,...,4.514201,1.171243,3.773565,20.619292,10.795486,20.266663,19.405815,10.484394,15.542376,11.568956
9251,3.064516,1,5,663.60,5,0,62.00,76.60,1.902117,36497.040,...,4.957363,0.907855,3.492408,20.619292,10.795486,20.266663,19.405815,10.484394,15.295068,11.568956
9260,4.672416,1,4,659.00,5,0,291.07,321.87,6.165909,22247.037,...,5.190533,1.993203,3.867402,20.410476,10.670466,20.119541,19.033880,10.581802,15.726829,10.925057

In [14]:
seoul_ua2_log.columns

Index(['rent_ua', '지하총층', '지상총층', '연면적m2', '주차대수', '승강기수', 'usage_area',
       'cont_area', '지하철거리m', '승객수점수', '건물별전기사용량', '본번별평균사용량', '횡단보도거리m',
       '건물연차', '가까운아파트총세대수', '가까운아파트평균평당가', '아파트거리', '주변세대수점수', '주변평당가점수',
       '평균월매출금액', '평균월매출건수', '평균주중매출금액', '평균주말매출금액', '편의점임대료', '공시지가',
       '행정동생활인구', '주차가능여부', '승강기여부', 'rent_ua_log', '연면적m2_log',
       'usage_area_log', 'cont_area_log', '지하철거리m_log', '승객수점수_log',
       '건물별전기사용량_log', '본번별평균사용량_log', '횡단보도거리m_log', '건물연차_log',
       '가까운아파트총세대수_log', '가까운아파트평균평당가_log', '아파트거리_log', '주변세대수점수_log',
       '주변평당가점수_log', '평균월매출금액_log', '평균월매출건수_log', '평균주중매출금액_log',
       '평균주말매출금액_log', '편의점임대료_log', '공시지가_log', '행정동생활인구_log'],
      dtype='object')

In [15]:
# 반로그함수 / 이상값 제거O(seoul_ua2_log), 설명변수: 연면적m2, usage_area, 공시지가, 평균주말매출금액

# 회귀분석 모듈 import

from statsmodels.formula.api import ols

# 모형 만들기
model = ols('rent_ua_log ~ usage_area + cont_area + 지하총층 + 지상총층 + 연면적m2 + 주차대수 + 승강기수 + 지하철거리m + 승객수점수 + 횡단보도거리m + 건물별전기사용량 + 본번별평균사용량 + 건물연차 + 공시지가 + 가까운아파트총세대수 + 가까운아파트평균평당가 + 아파트거리 + 주변세대수점수 + 주변평당가점수 + 평균월매출금액 + 평균월매출건수 + 평균주중매출금액 + 평균주말매출금액 + 편의점임대료 + 주차가능여부 + 승강기여부 + 행정동생활인구', seoul_ua2_log)

# 모형 적합
res = model.fit()

# 분석 결과 확인
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            rent_ua_log   R-squared:                       0.343
Model:                            OLS   Adj. R-squared:                  0.339
Method:                 Least Squares   F-statistic:                     86.14
Date:                Fri, 16 Oct 2020   Prob (F-statistic):               0.00
Time:                        10:35:15   Log-Likelihood:                -1857.9
No. Observations:                4474   AIC:                             3772.
Df Residuals:                    4446   BIC:                             3951.
Df Model:                          27
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept       0.8993      0.049     18.307      0.000       0.803       0.996
usage_area     -0.0013      0.000     -9.818      0.000      -0.002      -0.001
cont_area       0.0008      0.000      6.961      0.000       0.001       0.001
지하총층           -0.0485      0.015     -3.271      0.001      -0.078      -0.019
지상총층           -0.0049      0.006     -0.784      0.433      -0.017       0.007
연면적m2          -0.0002   2.17e-05     -7.119      0.000      -0.000      -0.000
주차대수            0.0068      0.003      2.486      0.013       0.001       0.012
승강기수           -0.0948      0.103     -0.925      0.355      -0.296       0.106
지하철거리m         -0.0084      0.003     -3.143      0.002      -0.014      -0.003
승객수점수         1.53e-06   1.99e-07      7.679      0.000    1.14e-06    1.92e-06
횡단보도거리m        -0.0008      0.000     -4.958      0.000      -0.001      -0.000
건물별전기사용량     1.511e-05    1.6e-06      9.427      0.000     1.2e-05    1.83e-05
본번별평균사용량     8.082e-06   1.39e-06      5.810      0.000    5.36e-06    1.08e-05
건물연차           -0.0022      0.001     -3.437      0.001      -0.004      -0.001
공시지가         6.459e-08   2.55e-09     25.324      0.000    5.96e-08    6.96e-08
가까운아파트총세대수  -2.087e-05   4.38e-05     -0.477      0.634      -0.000     6.5e-05
가까운아파트평균평당가   1.49e-05      1e-05      1.489      0.137   -4.73e-06    3.45e-05
아파트거리        4.326e-06   4.84e-05      0.089      0.929   -9.05e-05    9.92e-05
주변세대수점수        -0.0002      0.003     -0.057      0.955      -0.006       0.006
주변평당가점수         0.0002      0.001      0.427      0.669      -0.001       0.001
평균월매출금액        -0.0084      0.012     -0.724      0.469      -0.031       0.014
평균월매출건수      1.227e-06   5.25e-07      2.340      0.019    1.99e-07    2.26e-06
평균주중매출금액        0.0084      0.012      0.724      0.469      -0.014       0.031
평균주말매출금액        0.0084      0.012      0.724      0.469      -0.014       0.031
편의점임대료      -1.003e-08   1.78e-07     -0.056      0.955   -3.58e-07    3.38e-07
주차가능여부         -0.0542      0.017     -3.134      0.002      -0.088      -0.020
승강기여부           0.1534      0.106      1.450      0.147      -0.054       0.361
행정동생활인구     -1.841e-07   2.56e-07     -0.721      0.471   -6.85e-07    3.17e-07
==============================================================================
Omnibus:                      174.904   Durbin-Watson:                   1.882
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              372.675
Skew:                          -0.256   Prob(JB):                     1.19e-81
Kurtosis:                       4.318   Cond. No.                     3.96e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.96e+10. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [16]:
# 다중공선성 확인을 위한 모듈

from statsmodels.stats.outliers_influence import variance_inflation_factor

# 한번에 모든 컬럼의 VIF를 계산

pd.DataFrame({'컬럼': column, 'VIF': variance_inflation_factor(model.exog, i)} 
             for i, column in enumerate(model.exog_names)
             if column != 'Intercept')  # 절편의 VIF는 구하지 않는다.

C:\python\lib\site-packages\statsmodels\stats\outliers_influence.py:193: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

             컬럼        VIF
0    usage_area  11.911880
1     cont_area  12.133960
2          지하총층   1.257022
3          지상총층   2.556983
4         연면적m2   3.699910
5          주차대수   2.661052
6          승강기수  43.021701
7        지하철거리m   1.268614
8         승객수점수   1.472349
9       횡단보도거리m   1.100940
10     건물별전기사용량   2.128491
11     본번별평균사용량   1.341996
12         건물연차   2.006793
13         공시지가   1.738615
14   가까운아파트총세대수   1.561190
15  가까운아파트평균평당가   2.072893
16        아파트거리   1.729448
17      주변세대수점수   1.660196
18      주변평당가점수   2.764440
19      평균월매출금액        inf
20      평균월매출건수   4.823160
21     평균주중매출금액        inf
22     평균주말매출금액        inf
23       편의점임대료   1.219480
24       주차가능여부   2.476424
25        승강기여부  43.726196
26      행정동생활인구   1.202652

In [17]:
# 모형 만들기
model = ols('rent_ua_log ~ 연면적m2 + 공시지가 + 평균주말매출금액 + usage_area + 승객수점수 + 본번별평균사용량', seoul_ua2_log)

# 모형 적합
res = model.fit()

# 분석 결과 확인
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            rent_ua_log   R-squared:                       0.307
Model:                            OLS   Adj. R-squared:                  0.306
Method:                 Least Squares   F-statistic:                     329.3
Date:                Fri, 16 Oct 2020   Prob (F-statistic):               0.00
Time:                        10:35:15   Log-Likelihood:                -1979.9
No. Observations:                4474   AIC:                             3974.
Df Residuals:                    4467   BIC:                             4019.
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.6658      0.018     37.124      0.000       0.631       0.701
연면적m2      -4.497e-05   1.25e-05     -3.584      0.000   -6.96e-05   -2.04e-05
공시지가         6.69e-08   2.21e-09     30.234      0.000    6.26e-08    7.12e-08
평균주말매출금액    3.428e-10   4.42e-11      7.757      0.000    2.56e-10     4.3e-10
usage_area    -0.0005   4.13e-05    -11.284      0.000      -0.001      -0.000
승객수점수        1.88e-06   1.87e-07     10.068      0.000    1.51e-06    2.25e-06
본번별평균사용량    1.199e-05   1.34e-06      8.920      0.000    9.35e-06    1.46e-05
==============================================================================
Omnibus:                      154.774   Durbin-Watson:                   1.855
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              296.832
Skew:                          -0.257   Prob(JB):                     3.50e-65
Kurtosis:                       4.152   Cond. No.                     1.04e+09
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.04e+09. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [18]:
# 한번에 모든 컬럼의 VIF를 계산

pd.DataFrame({'컬럼': column, 'VIF': variance_inflation_factor(model.exog, i)} 
             for i, column in enumerate(model.exog_names)
             if column != 'Intercept')  # 절편의 VIF는 구하지 않는다.

           컬럼       VIF
0       연면적m2  1.179902
1        공시지가  1.245139
2    평균주말매출금액  1.171453
3  usage_area  1.094272
4       승객수점수  1.229475
5    본번별평균사용량  1.191999

In [19]:
# 회귀분석 모듈 import

from statsmodels.formula.api import ols

# 모형 만들기(with 모든변수)
model = ols('rent_ua_log ~ 연면적m2_log + usage_area_log+ cont_area_log+ 지하철거리m_log+ 승객수점수_log+ 건물별전기사용량_log+ 본번별평균사용량_log+ 횡단보도거리m_log+ 건물연차_log+ 가까운아파트총세대수_log+ 가까운아파트평균평당가_log+ 아파트거리_log+ 주변세대수점수_log+ 주변평당가점수_log+ 평균월매출금액_log+ 평균월매출건수_log+ 평균주중매출금액_log+ 평균주말매출금액_log+ 편의점임대료_log+ 공시지가_log+ 행정동생활인구_log+ 지하총층+ 지상총층+ 주차가능여부+ 승강기여부',  seoul_ua2_log)

# 모형 적합
res = model.fit()

# 분석 결과 확인
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            rent_ua_log   R-squared:                       0.379
Model:                            OLS   Adj. R-squared:                  0.376
Method:                 Least Squares   F-statistic:                     108.8
Date:                Fri, 16 Oct 2020   Prob (F-statistic):               0.00
Time:                        10:35:15   Log-Likelihood:                -1731.9
No. Observations:                4474   AIC:                             3516.
Df Residuals:                    4448   BIC:                             3682.
Df Model:                          25
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept          -7.3551      0.468    -15.716      0.000      -8.273      -6.438
연면적m2_log          -0.0903      0.013     -7.053      0.000      -0.115      -0.065
usage_area_log     -0.2564      0.024    -10.625      0.000      -0.304      -0.209
cont_area_log       0.1715      0.024      7.117      0.000       0.124       0.219
지하철거리m_log         -0.0337      0.010     -3.417      0.001      -0.053      -0.014
승객수점수_log           0.0682      0.009      7.465      0.000       0.050       0.086
건물별전기사용량_log        0.0446      0.007      6.438      0.000       0.031       0.058
본번별평균사용량_log        0.0650      0.009      7.575      0.000       0.048       0.082
횡단보도거리m_log        -0.0500      0.008     -6.055      0.000      -0.066      -0.034
건물연차_log           -0.0973      0.014     -6.999      0.000      -0.125      -0.070
가까운아파트총세대수_log      0.0050      0.008      0.641      0.522      -0.010       0.020
가까운아파트평균평당가_log    -0.0286      0.021     -1.358      0.175      -0.070       0.013
아파트거리_log           0.0017      0.014      0.122      0.903      -0.026       0.029
주변세대수점수_log        -0.0035      0.010     -0.355      0.723      -0.023       0.016
주변평당가점수_log         0.0134      0.019      0.710      0.478      -0.024       0.050
평균월매출금액_log         0.5784      0.610      0.948      0.343      -0.617       1.774
평균월매출건수_log         0.0233      0.033      0.712      0.476      -0.041       0.087
평균주중매출금액_log       -0.5320      0.453     -1.175      0.240      -1.419       0.355
평균주말매출금액_log       -0.0244      0.162     -0.150      0.881      -0.343       0.294
편의점임대료_log         -0.0066      0.011     -0.602      0.547      -0.028       0.015
공시지가_log            0.4963      0.018     28.090      0.000       0.462       0.531
행정동생활인구_log         0.0060      0.014      0.433      0.665      -0.021       0.033
지하총층               -0.0124      0.015     -0.823      0.411      -0.042       0.017
지상총층               -0.0020      0.006     -0.310      0.756      -0.014       0.010
주차가능여부             -0.0190      0.013     -1.445      0.148      -0.045       0.007
승강기여부               0.0177      0.020      0.882      0.378      -0.022       0.057
==============================================================================
Omnibus:                      196.771   Durbin-Watson:                   1.886
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              517.666
Skew:                          -0.213   Prob(JB):                    3.89e-113
Kurtosis:                       4.611   Cond. No.                     7.57e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.57e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [20]:
# 한번에 모든 컬럼의 VIF를 계산

pd.DataFrame({'컬럼': column, 'VIF': variance_inflation_factor(model.exog, i)} 
             for i, column in enumerate(model.exog_names)
             if column != 'Intercept')  # 절편의 VIF는 구하지 않는다.

                 컬럼          VIF
0         연면적m2_log     3.658516
1    usage_area_log    16.582418
2     cont_area_log    16.911163
3        지하철거리m_log     1.301527
4         승객수점수_log     1.596130
5      건물별전기사용량_log     1.976236
6      본번별평균사용량_log     1.472686
7       횡단보도거리m_log     1.111533
8          건물연차_log     1.796599
9    가까운아파트총세대수_log     1.760221
10  가까운아파트평균평당가_log     2.576575
11        아파트거리_log     2.300740
12      주변세대수점수_log     2.035620
13      주변평당가점수_log     4.421134
14      평균월매출금액_log  2814.192269
15      평균월매출건수_log     7.018368
16     평균주중매출금액_log  1522.270400
17     평균주말매출금액_log   236.098595
18       편의점임대료_log     1.232327
19         공시지가_log     1.910075
20      행정동생활인구_log     1.156555
21             지하총층     1.379585
22             지상총층     2.802309
23           주차가능여부     1.511790
24            승강기여부     1.663765

In [21]:
# 모형 만들기(usage_area, 공시지가, 매출, 전기사용량, 승객수점수)
model = ols('rent_ua_log ~ 공시지가_log + 평균주말매출금액_log + usage_area_log + 승객수점수_log + 본번별평균사용량_log', seoul_ua2_log)

# 모형 적합
res = model.fit()

# 분석 결과 확인
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            rent_ua_log   R-squared:                       0.340
Model:                            OLS   Adj. R-squared:                  0.339
Method:                 Least Squares   F-statistic:                     460.6
Date:                Fri, 16 Oct 2020   Prob (F-statistic):               0.00
Time:                        10:35:16   Log-Likelihood:                -1869.2
No. Observations:                4474   AIC:                             3750.
Df Residuals:                    4468   BIC:                             3789.
Df Model:                           5
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -8.6198      0.261    -33.010      0.000      -9.132      -8.108
공시지가_log           0.4845      0.015     33.032      0.000       0.456       0.513
평균주말매출금액_log       0.0665      0.012      5.575      0.000       0.043       0.090
usage_area_log    -0.1022      0.006    -16.269      0.000      -0.115      -0.090
승객수점수_log          0.0898      0.008     10.807      0.000       0.074       0.106
본번별평균사용량_log       0.0671      0.008      8.726      0.000       0.052       0.082
==============================================================================
Omnibus:                      179.598   Durbin-Watson:                   1.837
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              416.787
Skew:                          -0.233   Prob(JB):                     3.13e-91
Kurtosis:                       4.421   Cond. No.                     1.37e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.37e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [22]:
# 한번에 모든 컬럼의 VIF를 계산

pd.DataFrame({'컬럼': column, 'VIF': variance_inflation_factor(model.exog, i)} 
             for i, column in enumerate(model.exog_names)
             if column != 'Intercept')  # 절편의 VIF는 구하지 않는다.

               컬럼       VIF
0        공시지가_log  1.243622
1    평균주말매출금액_log  1.204498
2  usage_area_log  1.061224
3       승객수점수_log  1.247801
4    본번별평균사용량_log  1.117474

In [23]:
# 모형 만들기(usage_area, 공시지가, 매출)
model = ols('rent_ua_log ~ 공시지가_log + 평균주말매출금액_log + usage_area_log', seoul_ua2_log)

# 모형 적합
res = model.fit()

# 분석 결과 확인
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            rent_ua_log   R-squared:                       0.310
Model:                            OLS   Adj. R-squared:                  0.310
Method:                 Least Squares   F-statistic:                     670.7
Date:                Fri, 16 Oct 2020   Prob (F-statistic):               0.00
Time:                        10:35:16   Log-Likelihood:                -1967.7
No. Observations:                4474   AIC:                             3943.
Df Residuals:                    4470   BIC:                             3969.
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -9.0873      0.265    -34.350      0.000      -9.606      -8.569
공시지가_log           0.5512      0.014     38.868      0.000       0.523       0.579
평균주말매출금액_log       0.1116      0.012      9.552      0.000       0.089       0.135
usage_area_log    -0.0878      0.006    -13.865      0.000      -0.100      -0.075
==============================================================================
Omnibus:                      180.673   Durbin-Watson:                   1.815
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              449.008
Skew:                          -0.207   Prob(JB):                     3.16e-98
Kurtosis:                       4.496   Cond. No.                     1.19e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.19e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [24]:
# 한번에 모든 컬럼의 VIF를 계산

pd.DataFrame({'컬럼': column, 'VIF': variance_inflation_factor(model.exog, i)} 
             for i, column in enumerate(model.exog_names)
             if column != 'Intercept')  # 절편의 VIF는 구하지 않는다.

               컬럼       VIF
0        공시지가_log  1.112795
1    평균주말매출금액_log  1.105172
2  usage_area_log  1.031857

In [25]:
seoul_ua2_log.to_csv("C:/data/now_used/seoul_ua2_log.csv", index = False)