In [2]:
import pandas as pd
import numpy as np

In [3]:
seoul = pd.read_csv("C:/data/now_used/1019_data3.csv")

In [4]:
seoul

,건축물대장코드,구시군,읍면동,번,지,입주일,상가유형,지하총층,지상총층,연면적m2,...,주중평균유동인구수,주말평균유동인구수,유동인구비율_남성,유동인구비율_여성,유동인구비율_10대,유동인구비율_20대,유동인구비율_30대,유동인구비율_40대,유동인구비율_50대,유동인구비율_60대
0,11110-10014,종로구,동숭동,1,114,1982-12-24,근린상가,1,5,1563.66,...,107361.4,104675.0,48.45,51.55,5.72,32.38,20.42,15.86,13.85,11.77
1,11110-100180009,종로구,동숭동,1,67,2008-07-03,기타상가,4,5,8585.08,...,107361.4,104675.0,48.45,51.55,5.72,32.38,20.42,15.86,13.85,11.77
2,11110-100184402,종로구,관훈동,186,0,2008-12-29,근린상가,0,3,172.11,...,110721.0,85552.5,55.13,44.87,8.05,19.38,24.67,20.42,16.05,11.43
3,11110-100190514,종로구,누하동,245,6,2011-09-28,근린상가,0,4,233.03,...,107914.4,100200.5,43.75,56.25,9.80,27.03,21.65,18.11,14.18,9.23
4,11110-100190842,종로구,효제동,19,3,2011-10-14,근린상가,0,5,253.80,...,54434.8,39022.0,60.91,39.09,3.14,26.33,17.36,17.93,18.20,17.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9292,11740-9659,강동구,고덕동,645,4,1988-09-16,근린상가,1,4,493.71,...,70251.6,79761.0,51.23,48.77,12.09,14.55,19.07,20.31,18.67,15.31
9293,11740-9676,강동구,명일동,312,42,1980-06-27,근린상가,1,3,988.04,...,125081.0,147252.0,50.09,49.91,11.64,20.87,16.68,16.38,18.90,15.54
9294,11740-9698,강동구,명일동,326,11,1981-10-05,근린상가,1,2,741.99,...,125081.0,147252.0,50.09,49.91,11.64,20.87,16.68,16.38,18.90,15.54
9295,11740-9843,강동구,둔촌동,609,3,1993-12-06,근린상가,1,4,659.00,...,147089.2,138273.5,51.83,48.17,8.98,19.20,15.98,18.37,20.25,17.21
9296,11740-9917,강동구,길동,413,1,2002-02-06,기타상가,4,10,20582.74,...,241217.0,232032.0,50.27,49.73,4.02,22.24,20.62,18.40,19.17,15.54

In [5]:
seoul.columns

Index(['건축물대장코드', '구시군', '읍면동', '번', '지', '입주일', '상가유형', '지하총층', '지상총층',
       '연면적m2', '주차대수', '승강기수', '경도', '위도', 'usage_area', 'cont_area', 'RENT',
       'rent_ua', 'rent_ca', 'floor', '전철역명', '지하철거리m', '승객수점수', '건물별전기사용량',
       '본번별평균사용량', '횡단보도거리m', '건물연차', '가까운아파트', '가까운아파트총세대수', '가까운아파트평균평당가',
       '아파트거리', '주변세대수점수', '주변평당가점수', '상권코드명', '평균월매출금액', '평균월매출건수',
       '평균주중매출금액', '평균주말매출금액', '편의점임대료', '공시지가', '행정동생활인구', '토지면적', '도로접면',
       '도로추정크기', '총유동인구수', '주중평균유동인구수', '주말평균유동인구수', '유동인구비율_남성', '유동인구비율_여성',
       '유동인구비율_10대', '유동인구비율_20대', '유동인구비율_30대', '유동인구비율_40대', '유동인구비율_50대',
       '유동인구비율_60대'],
      dtype='object')

In [6]:
seoul_ua = seoul[['rent_ua', '지하총층', '지상총층',
       '연면적m2', '주차대수', '승강기수', 'usage_area', 'cont_area',
       '지하철거리m', '승객수점수', '건물별전기사용량',
       '본번별평균사용량', '횡단보도거리m', '건물연차', '가까운아파트총세대수', '가까운아파트평균평당가',
       '아파트거리', '주변세대수점수', '주변평당가점수', '평균월매출금액', '평균월매출건수',
       '평균주중매출금액', '평균주말매출금액', '편의점임대료', '공시지가', '행정동생활인구']]
seoul_ua.head()

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,주중평균유동인구수,주말평균유동인구수,유동인구비율_남성,유동인구비율_여성,유동인구비율_10대,유동인구비율_20대,유동인구비율_30대,유동인구비율_40대,유동인구비율_50대,유동인구비율_60대
0,48.387097,1,5,1563.66,0,1,15.50,15.50,1.082077,71533.898,...,107361.4,104675.0,48.45,51.55,5.72,32.38,20.42,15.86,13.85,11.77
1,13.155340,4,5,8585.08,7,4,103.00,143.92,1.373136,117064.164,...,107361.4,104675.0,48.45,51.55,5.72,32.38,20.42,15.86,13.85,11.77
2,11.891892,0,3,172.11,0,1,185.00,200.00,2.508637,46623.003,...,110721.0,85552.5,55.13,44.87,8.05,19.38,24.67,20.42,16.05,11.43
3,3.778770,0,4,233.03,2,0,58.22,58.22,4.791703,29040.490,...,107914.4,100200.5,43.75,56.25,9.80,27.03,21.65,18.11,14.18,9.23
4,2.037351,0,5,253.80,0,0,58.90,66.20,3.818611,34219.916,...,54434.8,39022.0,60.91,39.09,3.14,26.33,17.36,17.93,18.20,17.04

In [7]:
# 주차가능여부, 승강기여부 변수 추가
lst = []
[lst.append(1) if i > 0 else lst.append(0) for i in seoul_ua['주차대수']]

seoul_ua['주차가능여부'] = lst

lst = []
[lst.append(1) if i > 0 else lst.append(0) for i in seoul_ua['승강기수']]

seoul_ua['승강기여부'] = lst

seoul_ua

<ipython-input-7-f653761b9a8a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua['주차가능여부'] = lst
<ipython-input-7-f653761b9a8a>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua['승강기여부'] = lst

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,유동인구비율_남성,유동인구비율_여성,유동인구비율_10대,유동인구비율_20대,유동인구비율_30대,유동인구비율_40대,유동인구비율_50대,유동인구비율_60대,주차가능여부,승강기여부
0,48.387097,1,5,1563.66,0,1,15.50,15.50,1.082077,71533.898,...,48.45,51.55,5.72,32.38,20.42,15.86,13.85,11.77,0,1
1,13.155340,4,5,8585.08,7,4,103.00,143.92,1.373136,117064.164,...,48.45,51.55,5.72,32.38,20.42,15.86,13.85,11.77,1,1
2,11.891892,0,3,172.11,0,1,185.00,200.00,2.508637,46623.003,...,55.13,44.87,8.05,19.38,24.67,20.42,16.05,11.43,0,1
3,3.778770,0,4,233.03,2,0,58.22,58.22,4.791703,29040.490,...,43.75,56.25,9.80,27.03,21.65,18.11,14.18,9.23,1,0
4,2.037351,0,5,253.80,0,0,58.90,66.20,3.818611,34219.916,...,60.91,39.09,3.14,26.33,17.36,17.93,18.20,17.04,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9292,2.156190,1,4,493.71,3,0,783.79,891.83,4.357042,8921.374,...,51.23,48.77,12.09,14.55,19.07,20.31,18.67,15.31,1,0
9293,10.439427,1,3,988.04,0,0,41.19,41.19,0.729846,33569.452,...,50.09,49.91,11.64,20.87,16.68,16.38,18.90,15.54,0,0
9294,3.761755,1,2,741.99,4,0,127.60,127.60,2.046134,16942.142,...,50.09,49.91,11.64,20.87,16.68,16.38,18.90,15.54,1,0
9295,4.672416,1,4,659.00,5,0,291.07,321.87,6.165909,22247.037,...,51.83,48.17,8.98,19.20,15.98,18.37,20.25,17.21,1,0
9296,3.905050,4,10,20582.74,149,2,227.91,300.00,1.656423,90212.844,...,50.27,49.73,4.02,22.24,20.62,18.40,19.17,15.54,1,1

In [8]:
# 0값 제거
seoul_ua1 = seoul_ua.copy()

seoul_ua1 = seoul_ua1[seoul_ua1.rent_ua != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.지상총층 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.연면적m2 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.usage_area != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.cont_area != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.지하철거리m != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.승객수점수 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.건물별전기사용량 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.본번별평균사용량 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.횡단보도거리m != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.가까운아파트총세대수 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.가까운아파트평균평당가 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.아파트거리 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.주변세대수점수 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.주변평당가점수 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.평균월매출금액 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.평균월매출건수 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.평균주중매출금액 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.평균주말매출금액 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.공시지가 != 0]
seoul_ua1 = seoul_ua1[seoul_ua1.행정동생활인구 != 0]
seoul_ua1

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,유동인구비율_남성,유동인구비율_여성,유동인구비율_10대,유동인구비율_20대,유동인구비율_30대,유동인구비율_40대,유동인구비율_50대,유동인구비율_60대,주차가능여부,승강기여부
0,48.387097,1,5,1563.66,0,1,15.50,15.50,1.082077,71533.898,...,48.45,51.55,5.72,32.38,20.42,15.86,13.85,11.77,0,1
1,13.155340,4,5,8585.08,7,4,103.00,143.92,1.373136,117064.164,...,48.45,51.55,5.72,32.38,20.42,15.86,13.85,11.77,1,1
2,11.891892,0,3,172.11,0,1,185.00,200.00,2.508637,46623.003,...,55.13,44.87,8.05,19.38,24.67,20.42,16.05,11.43,0,1
3,3.778770,0,4,233.03,2,0,58.22,58.22,4.791703,29040.490,...,43.75,56.25,9.80,27.03,21.65,18.11,14.18,9.23,1,0
4,2.037351,0,5,253.80,0,0,58.90,66.20,3.818611,34219.916,...,60.91,39.09,3.14,26.33,17.36,17.93,18.20,17.04,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9292,2.156190,1,4,493.71,3,0,783.79,891.83,4.357042,8921.374,...,51.23,48.77,12.09,14.55,19.07,20.31,18.67,15.31,1,0
9293,10.439427,1,3,988.04,0,0,41.19,41.19,0.729846,33569.452,...,50.09,49.91,11.64,20.87,16.68,16.38,18.90,15.54,0,0
9294,3.761755,1,2,741.99,4,0,127.60,127.60,2.046134,16942.142,...,50.09,49.91,11.64,20.87,16.68,16.38,18.90,15.54,1,0
9295,4.672416,1,4,659.00,5,0,291.07,321.87,6.165909,22247.037,...,51.83,48.17,8.98,19.20,15.98,18.37,20.25,17.21,1,0
9296,3.905050,4,10,20582.74,149,2,227.91,300.00,1.656423,90212.844,...,50.27,49.73,4.02,22.24,20.62,18.40,19.17,15.54,1,1

In [8]:
# 이상값 제거
# 일반적으로는 iqt = 1.5 * (q3 - q1)로 정의. 하지만 너무 많은 데이터가 이상치로 빠지는 것을 막기 위해 iqt = 1.8 * (q3 - q1)로 정의하였다.

seoul_ua2 = seoul_ua1.copy()

q1 = seoul_ua2["rent_ua"].quantile(0.25)
q3 = seoul_ua2["rent_ua"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["rent_ua"][(seoul_ua2["rent_ua"] > (q3 + iqt)) | (seoul_ua2["rent_ua"] < (q1 - iqt))] = None

q1 = seoul_ua2["연면적m2"].quantile(0.25)
q3 = seoul_ua2["연면적m2"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["연면적m2"][(seoul_ua2["연면적m2"] > (q3 + iqt)) | (seoul_ua2["연면적m2"] < (q1 - iqt))] = None

q1 = seoul_ua2["usage_area"].quantile(0.25)
q3 = seoul_ua2["usage_area"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["usage_area"][(seoul_ua2["usage_area"] > (q3 + iqt)) | (seoul_ua2["usage_area"] < (q1 - iqt))] = None

q1 = seoul_ua2["cont_area"].quantile(0.25)
q3 = seoul_ua2["cont_area"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["cont_area"][(seoul_ua2["cont_area"] > (q3 + iqt)) | (seoul_ua2["cont_area"] < (q1 - iqt))] = None

q1 = seoul_ua2["지하철거리m"].quantile(0.25)
q3 = seoul_ua2["지하철거리m"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["지하철거리m"][(seoul_ua2["지하철거리m"] > (q3 + iqt)) | (seoul_ua2["지하철거리m"] < (q1 - iqt))] = None

q1 = seoul_ua2["승객수점수"].quantile(0.25)
q3 = seoul_ua2["승객수점수"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["승객수점수"][(seoul_ua2["승객수점수"] > (q3 + iqt)) | (seoul_ua2["승객수점수"] < (q1 - iqt))] = None

q1 = seoul_ua2["건물별전기사용량"].quantile(0.25)
q3 = seoul_ua2["건물별전기사용량"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["건물별전기사용량"][(seoul_ua2["건물별전기사용량"] > (q3 + iqt)) | (seoul_ua2["건물별전기사용량"] < (q1 - iqt))] = None

q1 = seoul_ua2["본번별평균사용량"].quantile(0.25)
q3 = seoul_ua2["본번별평균사용량"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["본번별평균사용량"][(seoul_ua2["본번별평균사용량"] > (q3 + iqt)) | (seoul_ua2["본번별평균사용량"] < (q1 - iqt))] = None

q1 = seoul_ua2["횡단보도거리m"].quantile(0.25)
q3 = seoul_ua2["횡단보도거리m"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["횡단보도거리m"][(seoul_ua2["횡단보도거리m"] > (q3 + iqt)) | (seoul_ua2["횡단보도거리m"] < (q1 - iqt))] = None

q1 = seoul_ua2["가까운아파트총세대수"].quantile(0.25)
q3 = seoul_ua2["가까운아파트총세대수"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["가까운아파트총세대수"][(seoul_ua2["가까운아파트총세대수"] > (q3 + iqt)) | (seoul_ua2["가까운아파트총세대수"] < (q1 - iqt))] = None

q1 = seoul_ua2["가까운아파트평균평당가"].quantile(0.25)
q3 = seoul_ua2["가까운아파트평균평당가"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["가까운아파트평균평당가"][(seoul_ua2["가까운아파트평균평당가"] > (q3 + iqt)) | (seoul_ua2["가까운아파트평균평당가"] < (q1 - iqt))] = None

q1 = seoul_ua2["아파트거리"].quantile(0.25)
q3 = seoul_ua2["아파트거리"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["아파트거리"][(seoul_ua2["아파트거리"] > (q3 + iqt)) | (seoul_ua2["아파트거리"] < (q1 - iqt))] = None

q1 = seoul_ua2["주변세대수점수"].quantile(0.25)
q3 = seoul_ua2["주변세대수점수"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["주변세대수점수"][(seoul_ua2["주변세대수점수"] > (q3 + iqt)) | (seoul_ua2["주변세대수점수"] < (q1 - iqt))] = None

q1 = seoul_ua2["주변평당가점수"].quantile(0.25)
q3 = seoul_ua2["주변평당가점수"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["주변평당가점수"][(seoul_ua2["주변평당가점수"] > (q3 + iqt)) | (seoul_ua2["주변평당가점수"] < (q1 - iqt))] = None

q1 = seoul_ua2["평균월매출금액"].quantile(0.25)
q3 = seoul_ua2["평균월매출금액"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["평균월매출금액"][(seoul_ua2["평균월매출금액"] > (q3 + iqt)) | (seoul_ua2["평균월매출금액"] < (q1 - iqt))] = None

q1 = seoul_ua2["평균월매출건수"].quantile(0.25)
q3 = seoul_ua2["평균월매출건수"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["평균월매출건수"][(seoul_ua2["평균월매출건수"] > (q3 + iqt)) | (seoul_ua2["평균월매출건수"] < (q1 - iqt))] = None

q1 = seoul_ua2["평균주중매출금액"].quantile(0.25)
q3 = seoul_ua2["평균주중매출금액"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["평균주중매출금액"][(seoul_ua2["평균주중매출금액"] > (q3 + iqt)) | (seoul_ua2["평균주중매출금액"] < (q1 - iqt))] = None

q1 = seoul_ua2["평균주말매출금액"].quantile(0.25)
q3 = seoul_ua2["평균주말매출금액"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["평균주말매출금액"][(seoul_ua2["평균주말매출금액"] > (q3 + iqt)) | (seoul_ua2["평균주말매출금액"] < (q1 - iqt))] = None

q1 = seoul_ua2["편의점임대료"].quantile(0.25)
q3 = seoul_ua2["편의점임대료"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["편의점임대료"][(seoul_ua2["편의점임대료"] > (q3 + iqt)) | (seoul_ua2["편의점임대료"] < (q1 - iqt))] = None

q1 = seoul_ua2["공시지가"].quantile(0.25)
q3 = seoul_ua2["공시지가"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["공시지가"][(seoul_ua2["공시지가"] > (q3 + iqt)) | (seoul_ua2["공시지가"] < (q1 - iqt))] = None

q1 = seoul_ua2["행정동생활인구"].quantile(0.25)
q3 = seoul_ua2["행정동생활인구"].quantile(0.75)
iqt = 1.8 * (q3 - q1)
seoul_ua2["행정동생활인구"][(seoul_ua2["행정동생활인구"] > (q3 + iqt)) | (seoul_ua2["행정동생활인구"] < (q1 - iqt))] = None


seoul_ua2 = seoul_ua2.dropna(axis = 0, how= 'any') # NaN값 제거를 변수 한 개의 이상값을 제거할 때마다 해주면 더 많은 데이터가 삭제되기 때문에 이상값 제거를 모두 마친 후 마지막에 한 번에 제거.

seoul_ua2

<ipython-input-8-d668468f1f8f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["rent_ua"][(seoul_ua2["rent_ua"] > (q3 + iqt)) | (seoul_ua2["rent_ua"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["연면적m2"][(seoul_ua2["연면적m2"] > (q3 + iqt)) | (seoul_ua2["연면적m2"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["usage_area"][(seoul_ua2["usage_area"] > (q3 + iqt)) | (seoul_ua2["usage_area"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["cont_area"][(seoul_ua2["cont_area"] > (q3 + iqt)) | (seoul_ua2["cont_area"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["지하철거리m"][(seoul_ua2["지하철거리m"] > (q3 + iqt)) | (seoul_ua2["지하철거리m"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["승객수점수"][(seoul_ua2["승객수점수"] > (q3 + iqt)) | (seoul_ua2["승객수점수"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["건물별전기사용량"][(seoul_ua2["건물별전기사용량"] > (q3 + iqt)) | (seoul_ua2["건물별전기사용량"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["본번별평균사용량"][(seoul_ua2["본번별평균사용량"] > (q3 + iqt)) | (seoul_ua2["본번별평균사용량"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["횡단보도거리m"][(seoul_ua2["횡단보도거리m"] > (q3 + iqt)) | (seoul_ua2["횡단보도거리m"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["가까운아파트총세대수"][(seoul_ua2["가까운아파트총세대수"] > (q3 + iqt)) | (seoul_ua2["가까운아파트총세대수"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["가까운아파트평균평당가"][(seoul_ua2["가까운아파트평균평당가"] > (q3 + iqt)) | (seoul_ua2["가까운아파트평균평당가"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["아파트거리"][(seoul_ua2["아파트거리"] > (q3 + iqt)) | (seoul_ua2["아파트거리"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["주변세대수점수"][(seoul_ua2["주변세대수점수"] > (q3 + iqt)) | (seoul_ua2["주변세대수점수"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["주변평당가점수"][(seoul_ua2["주변평당가점수"] > (q3 + iqt)) | (seoul_ua2["주변평당가점수"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["평균월매출금액"][(seoul_ua2["평균월매출금액"] > (q3 + iqt)) | (seoul_ua2["평균월매출금액"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["평균월매출건수"][(seoul_ua2["평균월매출건수"] > (q3 + iqt)) | (seoul_ua2["평균월매출건수"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["평균주중매출금액"][(seoul_ua2["평균주중매출금액"] > (q3 + iqt)) | (seoul_ua2["평균주중매출금액"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:94: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["평균주말매출금액"][(seoul_ua2["평균주말매출금액"] > (q3 + iqt)) | (seoul_ua2["평균주말매출금액"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["편의점임대료"][(seoul_ua2["편의점임대료"] > (q3 + iqt)) | (seoul_ua2["편의점임대료"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["공시지가"][(seoul_ua2["공시지가"] > (q3 + iqt)) | (seoul_ua2["공시지가"] < (q1 - iqt))] = None
<ipython-input-8-d668468f1f8f>:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_ua2["행정동생활인구"][(seoul_ua2["행정동생활인구"] > (q3 + iqt)) | (seoul_ua2["행정동생활인구"] < (q1 - iqt))] = None

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,주변평당가점수,평균월매출금액,평균월매출건수,평균주중매출금액,평균주말매출금액,편의점임대료,공시지가,행정동생활인구,주차가능여부,승강기여부
3,3.778770,0,4,233.03,2,0,58.22,58.22,4.791703,29040.490,...,16.353,1.266094e+09,59989.0,952608422.0,313485211.0,67634.444078,7727000.0,40687.0,1,0
4,2.037351,0,5,253.80,0,0,58.90,66.20,3.818611,34219.916,...,10.063,7.012839e+08,59235.0,586470792.0,114813136.0,112721.417069,4878000.0,30695.0,0,0
9,4.792551,1,4,458.95,0,0,73.03,73.03,3.944218,24836.371,...,14.742,1.132740e+09,82393.0,810808853.0,321931432.0,95483.870968,8977000.0,55931.0,0,0
15,2.249335,1,3,480.67,0,0,146.71,146.71,3.241511,60826.450,...,7.496,1.276470e+09,92138.0,926358383.0,350111420.0,85005.100306,6848000.0,38293.0,0,0
17,5.451242,1,4,503.46,3,0,99.06,127.74,3.672770,18686.432,...,14.908,1.266094e+09,59989.0,952608422.0,313485211.0,90696.313634,9104000.0,29924.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9247,2.861953,0,5,675.70,5,0,59.40,66.40,4.533248,16690.231,...,52.278,1.194210e+09,67939.0,923563626.0,270646039.0,79175.105874,5443000.0,52160.0,1,0
9248,3.083906,1,3,410.52,2,0,85.93,239.03,7.958086,10810.675,...,25.011,5.051960e+08,29735.0,366639062.0,138556963.0,43392.132818,6388000.0,67018.0,1,0
9249,2.352941,1,3,662.36,4,0,59.50,82.64,2.570816,30563.172,...,43.535,9.012489e+08,48800.0,633431615.0,267817266.0,35753.147831,5623000.0,105763.0,1,0
9251,3.064516,1,5,663.60,5,0,62.00,76.60,1.902117,36497.040,...,32.865,9.012489e+08,48800.0,633431615.0,267817266.0,35753.147831,4391000.0,105763.0,1,0
9260,4.672416,1,4,659.00,5,0,291.07,321.87,6.165909,22247.037,...,47.818,7.314037e+08,43065.0,546770943.0,184632806.0,39411.064842,6762000.0,55551.0,1,0

In [9]:
seoul_ua2_log = seoul_ua2.copy()
seoul_ua2_log

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,주변평당가점수,평균월매출금액,평균월매출건수,평균주중매출금액,평균주말매출금액,편의점임대료,공시지가,행정동생활인구,주차가능여부,승강기여부
3,3.778770,0,4,233.03,2,0,58.22,58.22,4.791703,29040.490,...,16.353,1.266094e+09,59989.0,952608422.0,313485211.0,67634.444078,7727000.0,40687.0,1,0
4,2.037351,0,5,253.80,0,0,58.90,66.20,3.818611,34219.916,...,10.063,7.012839e+08,59235.0,586470792.0,114813136.0,112721.417069,4878000.0,30695.0,0,0
9,4.792551,1,4,458.95,0,0,73.03,73.03,3.944218,24836.371,...,14.742,1.132740e+09,82393.0,810808853.0,321931432.0,95483.870968,8977000.0,55931.0,0,0
15,2.249335,1,3,480.67,0,0,146.71,146.71,3.241511,60826.450,...,7.496,1.276470e+09,92138.0,926358383.0,350111420.0,85005.100306,6848000.0,38293.0,0,0
17,5.451242,1,4,503.46,3,0,99.06,127.74,3.672770,18686.432,...,14.908,1.266094e+09,59989.0,952608422.0,313485211.0,90696.313634,9104000.0,29924.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9247,2.861953,0,5,675.70,5,0,59.40,66.40,4.533248,16690.231,...,52.278,1.194210e+09,67939.0,923563626.0,270646039.0,79175.105874,5443000.0,52160.0,1,0
9248,3.083906,1,3,410.52,2,0,85.93,239.03,7.958086,10810.675,...,25.011,5.051960e+08,29735.0,366639062.0,138556963.0,43392.132818,6388000.0,67018.0,1,0
9249,2.352941,1,3,662.36,4,0,59.50,82.64,2.570816,30563.172,...,43.535,9.012489e+08,48800.0,633431615.0,267817266.0,35753.147831,5623000.0,105763.0,1,0
9251,3.064516,1,5,663.60,5,0,62.00,76.60,1.902117,36497.040,...,32.865,9.012489e+08,48800.0,633431615.0,267817266.0,35753.147831,4391000.0,105763.0,1,0
9260,4.672416,1,4,659.00,5,0,291.07,321.87,6.165909,22247.037,...,47.818,7.314037e+08,43065.0,546770943.0,184632806.0,39411.064842,6762000.0,55551.0,1,0

In [10]:
# 요약 통계량 확인하기

seoul_ua2_log = seoul_ua2_log[seoul_ua2_log['연면적m2'] != 0]
seoul_ua2_log.describe()

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,주변평당가점수,평균월매출금액,평균월매출건수,평균주중매출금액,평균주말매출금액,편의점임대료,공시지가,행정동생활인구,주차가능여부,승강기여부
count,4474.000000,4474.000000,4474.000000,4474.000000,4474.000000,4474.000000,4474.000000,4474.000000,4474.000000,4474.000000,...,4474.000000,4.474000e+03,4474.000000,4.474000e+03,4.474000e+03,4474.000000,4.474000e+03,4474.000000,4474.000000,4474.000000
mean,3.879297,0.863880,3.797273,662.414389,2.402325,0.138355,158.757300,181.684799,4.370455,46063.046057,...,27.895469,1.088481e+09,58093.952168,7.920690e+08,2.964118e+08,60532.869536,6.402881e+06,54904.991283,0.510729,0.136790
std,1.783621,0.415469,1.409235,488.009323,3.300029,0.351725,142.925113,164.783598,2.323820,33471.993796,...,16.779590,4.380602e+08,23018.818752,3.156274e+08,1.380142e+08,34174.628736,2.842300e+06,23590.646315,0.499941,0.343664
min,0.297063,0.000000,1.000000,12.030000,0.000000,0.000000,6.000000,8.000000,0.183268,3073.198000,...,4.556000,1.119613e+08,6561.000000,8.237247e+07,2.958881e+07,3156.167151,6.760000e+04,9970.000000,0.000000,0.000000
25%,2.597403,1.000000,3.000000,316.035000,0.000000,0.000000,56.000000,63.772500,2.570710,21323.118250,...,15.681250,7.394747e+08,41405.000000,5.561323e+08,1.904996e+08,35753.147831,4.350000e+06,38287.000000,0.000000,0.000000
50%,3.493797,1.000000,4.000000,539.360000,1.000000,0.000000,105.805000,122.380000,4.053790,36101.665000,...,23.263000,1.077646e+09,56100.000000,7.819209e+08,2.764897e+08,50639.321433,5.662000e+06,50219.000000,1.000000,0.000000
75%,4.786422,1.000000,5.000000,871.320000,4.000000,0.000000,208.882500,241.665000,5.759044,61522.920500,...,36.439750,1.384609e+09,72469.000000,1.023801e+09,3.707628e+08,77808.670702,7.756000e+06,68663.000000,1.000000,0.000000
max,10.892587,3.000000,11.000000,2823.450000,69.000000,4.000000,720.740000,874.300000,11.744879,179012.864000,...,87.925000,2.137533e+09,142885.000000,1.620105e+09,8.670086e+08,189181.200118,1.900000e+07,124552.000000,1.000000,1.000000

In [11]:
seoul_ua2_log.columns

Index(['rent_ua', '지하총층', '지상총층', '연면적m2', '주차대수', '승강기수', 'usage_area',
       'cont_area', '지하철거리m', '승객수점수', '건물별전기사용량', '본번별평균사용량', '횡단보도거리m',
       '건물연차', '가까운아파트총세대수', '가까운아파트평균평당가', '아파트거리', '주변세대수점수', '주변평당가점수',
       '평균월매출금액', '평균월매출건수', '평균주중매출금액', '평균주말매출금액', '편의점임대료', '공시지가',
       '행정동생활인구', '주차가능여부', '승강기여부'],
      dtype='object')

In [12]:
columns = ['rent_ua', '연면적m2', 'usage_area',
       'cont_area', '지하철거리m', '승객수점수', '건물별전기사용량', '본번별평균사용량', '횡단보도거리m',
       '건물연차', '가까운아파트총세대수', '가까운아파트평균평당가', '아파트거리', '주변세대수점수', '주변평당가점수',
       '평균월매출금액', '평균월매출건수', '평균주중매출금액', '평균주말매출금액', '편의점임대료', '공시지가',
       '행정동생활인구']

In [13]:
# columns에 담긴 변수 log 취하고 scaling

import math
from sklearn import preprocessing

for i in columns:
    seoul_ua2_log['{}_log'.format(i)] = preprocessing.scale(np.log(seoul_ua2_log['{}'.format(i)]))
    
seoul_ua2_log

,rent_ua,지하총층,지상총층,연면적m2,주차대수,승강기수,usage_area,cont_area,지하철거리m,승객수점수,...,아파트거리_log,주변세대수점수_log,주변평당가점수_log,평균월매출금액_log,평균월매출건수_log,평균주중매출금액_log,평균주말매출금액_log,편의점임대료_log,공시지가_log,행정동생활인구_log
3,3.778770,0,4,233.03,2,0,58.22,58.22,4.791703,29040.490,...,0.937532,-0.181361,-0.605355,0.531107,0.272794,0.604495,0.342334,0.469517,0.659573,-0.515257
4,2.037351,0,5,253.80,0,0,58.90,66.20,3.818611,34219.916,...,1.182769,-1.349804,-1.419410,-0.739976,0.243608,-0.448655,-1.644429,1.407613,-0.440991,-1.194152
9,4.792551,1,4,458.95,0,0,73.03,73.03,3.944218,24836.371,...,0.923106,-0.411272,-0.779234,0.291649,1.005030,0.254579,0.394921,1.102821,1.018332,0.251332
15,2.249335,1,3,480.67,0,0,146.71,146.71,3.241511,60826.450,...,1.796350,-0.351212,-1.913154,0.548668,1.262969,0.543829,0.560898,0.889334,0.370632,-0.661346
17,5.451242,1,4,503.46,3,0,99.06,127.74,3.672770,18686.432,...,1.422751,-0.528237,-0.760461,0.531107,0.272794,0.604495,0.342334,1.008350,1.051943,-1.255436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9247,2.861953,0,5,675.70,5,0,59.40,66.40,4.533248,16690.231,...,-3.076236,-0.092574,1.343100,0.405346,0.559950,0.537269,0.051691,0.758850,-0.178773,0.083172
9248,3.083906,1,3,410.52,2,0,85.93,239.03,7.958086,10810.675,...,-0.195730,0.338587,0.107029,-1.445609,-1.346640,-1.468509,-1.272619,-0.345600,0.204261,0.686993
9249,2.352941,1,3,662.36,4,0,59.50,82.64,2.570816,30563.172,...,-1.735930,0.457789,1.036270,-0.200223,-0.203530,-0.281418,0.030908,-0.701222,-0.100930,1.786103
9251,3.064516,1,5,663.60,5,0,62.00,76.60,1.902117,36497.040,...,-0.967688,0.113281,0.564889,-0.200223,-0.203530,-0.281418,0.030908,-0.701222,-0.692641,1.786103
9260,4.672416,1,4,659.00,5,0,291.07,321.87,6.165909,22247.037,...,-0.563476,1.532903,1.193594,-0.649498,-0.492003,-0.600832,-0.704769,-0.522331,0.340394,0.234908

In [14]:
seoul_ua2_log.columns

Index(['rent_ua', '지하총층', '지상총층', '연면적m2', '주차대수', '승강기수', 'usage_area',
       'cont_area', '지하철거리m', '승객수점수', '건물별전기사용량', '본번별평균사용량', '횡단보도거리m',
       '건물연차', '가까운아파트총세대수', '가까운아파트평균평당가', '아파트거리', '주변세대수점수', '주변평당가점수',
       '평균월매출금액', '평균월매출건수', '평균주중매출금액', '평균주말매출금액', '편의점임대료', '공시지가',
       '행정동생활인구', '주차가능여부', '승강기여부', 'rent_ua_log', '연면적m2_log',
       'usage_area_log', 'cont_area_log', '지하철거리m_log', '승객수점수_log',
       '건물별전기사용량_log', '본번별평균사용량_log', '횡단보도거리m_log', '건물연차_log',
       '가까운아파트총세대수_log', '가까운아파트평균평당가_log', '아파트거리_log', '주변세대수점수_log',
       '주변평당가점수_log', '평균월매출금액_log', '평균월매출건수_log', '평균주중매출금액_log',
       '평균주말매출금액_log', '편의점임대료_log', '공시지가_log', '행정동생활인구_log'],
      dtype='object')

In [15]:
# 반로그함수 / 이상값 제거O(seoul_ua2_log), 설명변수: 연면적m2, usage_area, 공시지가, 평균주말매출금액

# 회귀분석 모듈 import

from statsmodels.formula.api import ols

# 모형 만들기
model = ols('rent_ua_log ~ usage_area + cont_area + 지하총층 + 지상총층 + 연면적m2 + 주차대수 + 승강기수 + 지하철거리m + 승객수점수 + 횡단보도거리m + 건물별전기사용량 + 본번별평균사용량 + 건물연차 + 공시지가 + 가까운아파트총세대수 + 가까운아파트평균평당가 + 아파트거리 + 주변세대수점수 + 주변평당가점수 + 평균월매출금액 + 평균월매출건수 + 평균주중매출금액 + 평균주말매출금액 + 편의점임대료 + 주차가능여부 + 승강기여부 + 행정동생활인구', seoul_ua2_log)

# 모형 적합
res = model.fit()

# 분석 결과 확인
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            rent_ua_log   R-squared:                       0.343
Model:                            OLS   Adj. R-squared:                  0.339
Method:                 Least Squares   F-statistic:                     86.14
Date:                Fri, 16 Oct 2020   Prob (F-statistic):               0.00
Time:                        13:26:11   Log-Likelihood:                -5407.1
No. Observations:                4474   AIC:                         1.087e+04
Df Residuals:                    4446   BIC:                         1.105e+04
Df Model:                          27
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      -0.7869      0.109     -7.247      0.000      -1.000      -0.574
usage_area     -0.0029      0.000     -9.818      0.000      -0.003      -0.002
cont_area       0.0018      0.000      6.961      0.000       0.001       0.002
지하총층           -0.1073      0.033     -3.271      0.001      -0.172      -0.043
지상총층           -0.0108      0.014     -0.784      0.433      -0.038       0.016
연면적m2          -0.0003   4.79e-05     -7.119      0.000      -0.000      -0.000
주차대수            0.0149      0.006      2.486      0.013       0.003       0.027
승강기수           -0.2096      0.227     -0.925      0.355      -0.654       0.235
지하철거리m         -0.0185      0.006     -3.143      0.002      -0.030      -0.007
승객수점수        3.383e-06   4.41e-07      7.679      0.000    2.52e-06    4.25e-06
횡단보도거리m        -0.0018      0.000     -4.958      0.000      -0.003      -0.001
건물별전기사용량     3.341e-05   3.54e-06      9.427      0.000    2.65e-05    4.04e-05
본번별평균사용량     1.787e-05   3.08e-06      5.810      0.000    1.18e-05    2.39e-05
건물연차           -0.0050      0.001     -3.437      0.001      -0.008      -0.002
공시지가         1.428e-07   5.64e-09     25.324      0.000    1.32e-07    1.54e-07
가까운아파트총세대수  -4.614e-05   9.68e-05     -0.477      0.634      -0.000       0.000
가까운아파트평균평당가  3.295e-05   2.21e-05      1.489      0.137   -1.04e-05    7.63e-05
아파트거리        9.563e-06      0.000      0.089      0.929      -0.000       0.000
주변세대수점수        -0.0004      0.007     -0.057      0.955      -0.014       0.013
주변평당가점수         0.0005      0.001      0.427      0.669      -0.002       0.003
평균월매출금액        -0.0185      0.026     -0.724      0.469      -0.069       0.032
평균월매출건수      2.714e-06   1.16e-06      2.340      0.019     4.4e-07    4.99e-06
평균주중매출금액        0.0185      0.026      0.724      0.469      -0.032       0.069
평균주말매출금액        0.0185      0.026      0.724      0.469      -0.032       0.069
편의점임대료      -2.217e-08   3.93e-07     -0.056      0.955   -7.92e-07    7.48e-07
주차가능여부         -0.1199      0.038     -3.134      0.002      -0.195      -0.045
승강기여부           0.3390      0.234      1.450      0.147      -0.119       0.797
행정동생활인구     -4.071e-07   5.65e-07     -0.721      0.471   -1.51e-06    7.01e-07
==============================================================================
Omnibus:                      174.904   Durbin-Watson:                   1.882
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              372.675
Skew:                          -0.256   Prob(JB):                     1.19e-81
Kurtosis:                       4.318   Cond. No.                     3.96e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.96e+10. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [16]:
# 다중공선성 확인을 위한 모듈

from statsmodels.stats.outliers_influence import variance_inflation_factor

# 한번에 모든 컬럼의 VIF를 계산

pd.DataFrame({'컬럼': column, 'VIF': variance_inflation_factor(model.exog, i)} 
             for i, column in enumerate(model.exog_names)
             if column != 'Intercept')  # 절편의 VIF는 구하지 않는다.

C:\python\lib\site-packages\statsmodels\stats\outliers_influence.py:193: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

             컬럼        VIF
0    usage_area  11.911880
1     cont_area  12.133960
2          지하총층   1.257022
3          지상총층   2.556983
4         연면적m2   3.699910
5          주차대수   2.661052
6          승강기수  43.021701
7        지하철거리m   1.268614
8         승객수점수   1.472349
9       횡단보도거리m   1.100940
10     건물별전기사용량   2.128491
11     본번별평균사용량   1.341996
12         건물연차   2.006793
13         공시지가   1.738615
14   가까운아파트총세대수   1.561190
15  가까운아파트평균평당가   2.072893
16        아파트거리   1.729448
17      주변세대수점수   1.660196
18      주변평당가점수   2.764440
19      평균월매출금액        inf
20      평균월매출건수   4.823160
21     평균주중매출금액        inf
22     평균주말매출금액        inf
23       편의점임대료   1.219480
24       주차가능여부   2.476424
25        승강기여부  43.726196
26      행정동생활인구   1.202652

In [17]:
# 모형 만들기
model = ols('rent_ua_log ~ 연면적m2 + 공시지가 + 평균주말매출금액 + usage_area + 승객수점수 + 본번별평균사용량', seoul_ua2_log)

# 모형 적합
res = model.fit()

# 분석 결과 확인
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            rent_ua_log   R-squared:                       0.307
Model:                            OLS   Adj. R-squared:                  0.306
Method:                 Least Squares   F-statistic:                     329.3
Date:                Fri, 16 Oct 2020   Prob (F-statistic):               0.00
Time:                        13:26:12   Log-Likelihood:                -5529.1
No. Observations:                4474   AIC:                         1.107e+04
Df Residuals:                    4467   BIC:                         1.112e+04
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -1.3030      0.040    -32.864      0.000      -1.381      -1.225
연면적m2       -9.94e-05   2.77e-05     -3.584      0.000      -0.000    -4.5e-05
공시지가        1.479e-07   4.89e-09     30.234      0.000    1.38e-07    1.57e-07
평균주말매출금액    7.579e-10   9.77e-11      7.757      0.000    5.66e-10    9.49e-10
usage_area    -0.0010   9.12e-05    -11.284      0.000      -0.001      -0.001
승객수점수       4.156e-06   4.13e-07     10.068      0.000    3.35e-06    4.96e-06
본번별평균사용량     2.65e-05   2.97e-06      8.920      0.000    2.07e-05    3.23e-05
==============================================================================
Omnibus:                      154.774   Durbin-Watson:                   1.855
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              296.832
Skew:                          -0.257   Prob(JB):                     3.50e-65
Kurtosis:                       4.152   Cond. No.                     1.04e+09
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.04e+09. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [18]:
# 한번에 모든 컬럼의 VIF를 계산

pd.DataFrame({'컬럼': column, 'VIF': variance_inflation_factor(model.exog, i)} 
             for i, column in enumerate(model.exog_names)
             if column != 'Intercept')  # 절편의 VIF는 구하지 않는다.

           컬럼       VIF
0       연면적m2  1.179902
1        공시지가  1.245139
2    평균주말매출금액  1.171453
3  usage_area  1.094272
4       승객수점수  1.229475
5    본번별평균사용량  1.191999

In [19]:
# 회귀분석 모듈 import

from statsmodels.formula.api import ols

# 모형 만들기(with 모든변수)
model = ols('rent_ua_log ~ 연면적m2_log + usage_area_log+ cont_area_log+ 지하철거리m_log+ 승객수점수_log+ 건물별전기사용량_log+ 본번별평균사용량_log+ 횡단보도거리m_log+ 건물연차_log+ 가까운아파트총세대수_log+ 가까운아파트평균평당가_log+ 아파트거리_log+ 주변세대수점수_log+ 주변평당가점수_log+ 평균월매출금액_log+ 평균월매출건수_log+ 평균주중매출금액_log+ 평균주말매출금액_log+ 편의점임대료_log+ 공시지가_log+ 행정동생활인구_log+ 지하총층+ 지상총층+ 주차가능여부+ 승강기여부',  seoul_ua2_log)

# 모형 적합
res = model.fit()

# 분석 결과 확인
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            rent_ua_log   R-squared:                       0.379
Model:                            OLS   Adj. R-squared:                  0.376
Method:                 Least Squares   F-statistic:                     108.8
Date:                Fri, 16 Oct 2020   Prob (F-statistic):               0.00
Time:                        13:26:12   Log-Likelihood:                -5281.2
No. Observations:                4474   AIC:                         1.061e+04
Df Residuals:                    4448   BIC:                         1.078e+04
Df Model:                          25
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept           0.0564      0.061      0.926      0.355      -0.063       0.176
연면적m2_log          -0.1594      0.023     -7.053      0.000      -0.204      -0.115
usage_area_log     -0.5111      0.048    -10.625      0.000      -0.605      -0.417
cont_area_log       0.3457      0.049      7.117      0.000       0.250       0.441
지하철거리m_log         -0.0460      0.013     -3.417      0.001      -0.072      -0.020
승객수점수_log           0.1114      0.015      7.465      0.000       0.082       0.141
건물별전기사용량_log        0.1069      0.017      6.438      0.000       0.074       0.139
본번별평균사용량_log        0.1086      0.014      7.575      0.000       0.080       0.137
횡단보도거리m_log        -0.0754      0.012     -6.055      0.000      -0.100      -0.051
건물연차_log           -0.1108      0.016     -6.999      0.000      -0.142      -0.080
가까운아파트총세대수_log      0.0100      0.016      0.641      0.522      -0.021       0.041
가까운아파트평균평당가_log    -0.0257      0.019     -1.358      0.175      -0.063       0.011
아파트거리_log           0.0022      0.018      0.122      0.903      -0.033       0.037
주변세대수점수_log        -0.0060      0.017     -0.355      0.723      -0.039       0.027
주변평당가점수_log         0.0176      0.025      0.710      0.478      -0.031       0.066
평균월매출금액_log         0.5943      0.627      0.948      0.343      -0.634       1.823
평균월매출건수_log         0.0223      0.031      0.712      0.476      -0.039       0.084
평균주중매출금액_log       -0.5417      0.461     -1.175      0.240      -1.445       0.362
평균주말매출금액_log       -0.0273      0.181     -0.150      0.881      -0.383       0.329
편의점임대료_log         -0.0079      0.013     -0.602      0.547      -0.034       0.018
공시지가_log            0.4586      0.016     28.090      0.000       0.427       0.491
행정동생활인구_log         0.0055      0.013      0.433      0.665      -0.019       0.030
지하총층               -0.0275      0.033     -0.823      0.411      -0.093       0.038
지상총층               -0.0044      0.014     -0.310      0.756      -0.032       0.023
주차가능여부             -0.0420      0.029     -1.445      0.148      -0.099       0.015
승강기여부               0.0391      0.044      0.882      0.378      -0.048       0.126
==============================================================================
Omnibus:                      196.771   Durbin-Watson:                   1.886
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              517.666
Skew:                          -0.213   Prob(JB):                    3.89e-113
Kurtosis:                       4.611   Cond. No.                         291.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [20]:
# 한번에 모든 컬럼의 VIF를 계산

pd.DataFrame({'컬럼': column, 'VIF': variance_inflation_factor(model.exog, i)} 
             for i, column in enumerate(model.exog_names)
             if column != 'Intercept')  # 절편의 VIF는 구하지 않는다.

                 컬럼          VIF
0         연면적m2_log     3.658516
1    usage_area_log    16.582418
2     cont_area_log    16.911163
3        지하철거리m_log     1.301527
4         승객수점수_log     1.596130
5      건물별전기사용량_log     1.976236
6      본번별평균사용량_log     1.472686
7       횡단보도거리m_log     1.111533
8          건물연차_log     1.796599
9    가까운아파트총세대수_log     1.760221
10  가까운아파트평균평당가_log     2.576575
11        아파트거리_log     2.300740
12      주변세대수점수_log     2.035620
13      주변평당가점수_log     4.421134
14      평균월매출금액_log  2814.192269
15      평균월매출건수_log     7.018368
16     평균주중매출금액_log  1522.270400
17     평균주말매출금액_log   236.098595
18       편의점임대료_log     1.232327
19         공시지가_log     1.910075
20      행정동생활인구_log     1.156555
21             지하총층     1.379585
22             지상총층     2.802309
23           주차가능여부     1.511790
24            승강기여부     1.663765

In [21]:
# 회귀분석 모듈 import

from statsmodels.formula.api import ols

# 모형 만들기(with 다중공선성 10이상, p-value > 0.05 변수 제외)
model = ols('rent_ua_log ~ 연면적m2_log + usage_area_log+ 지하철거리m_log+ 승객수점수_log+ 건물별전기사용량_log+ 본번별평균사용량_log+ 횡단보도거리m_log+ 건물연차_log+ 평균월매출금액_log+ 공시지가_log',  seoul_ua2_log)

# 모형 적합
res = model.fit()

# 분석 결과 확인
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            rent_ua_log   R-squared:                       0.368
Model:                            OLS   Adj. R-squared:                  0.367
Method:                 Least Squares   F-statistic:                     260.4
Date:                Fri, 16 Oct 2020   Prob (F-statistic):               0.00
Time:                        13:26:12   Log-Likelihood:                -5320.2
No. Observations:                4474   AIC:                         1.066e+04
Df Residuals:                    4463   BIC:                         1.073e+04
Df Model:                          10
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept       4.836e-16      0.012   4.06e-14      1.000      -0.023       0.023
연면적m2_log         -0.1744      0.016    -10.910      0.000      -0.206      -0.143
usage_area_log    -0.1797      0.013    -14.198      0.000      -0.205      -0.155
지하철거리m_log        -0.0395      0.013     -2.944      0.003      -0.066      -0.013
승객수점수_log          0.1179      0.015      8.043      0.000       0.089       0.147
건물별전기사용량_log       0.1130      0.016      6.888      0.000       0.081       0.145
본번별평균사용량_log       0.1092      0.014      7.646      0.000       0.081       0.137
횡단보도거리m_log       -0.0812      0.012     -6.642      0.000      -0.105      -0.057
건물연차_log          -0.1134      0.013     -9.002      0.000      -0.138      -0.089
평균월매출금액_log        0.0530      0.014      3.873      0.000       0.026       0.080
공시지가_log           0.4499      0.014     32.790      0.000       0.423       0.477
==============================================================================
Omnibus:                      170.524   Durbin-Watson:                   1.887
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              412.641
Skew:                          -0.198   Prob(JB):                     2.49e-90
Kurtosis:                       4.434   Cond. No.                         2.77
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [22]:
# 한번에 모든 컬럼의 VIF를 계산

pd.DataFrame({'컬럼': column, 'VIF': variance_inflation_factor(model.exog, i)} 
             for i, column in enumerate(model.exog_names)
             if column != 'Intercept')  # 절편의 VIF는 구하지 않는다.

               컬럼       VIF
0       연면적m2_log  1.806540
1  usage_area_log  1.132342
2      지하철거리m_log  1.274719
3       승객수점수_log  1.518968
4    건물별전기사용량_log  1.901801
5    본번별평균사용량_log  1.440640
6     횡단보도거리m_log  1.055032
7        건물연차_log  1.120592
8     평균월매출금액_log  1.323709
9        공시지가_log  1.330106

In [23]:
# 모형 만들기(연면적m2, usage_area, 공시지가, 매출, 전기사용량, 승객수점수)
model = ols('rent_ua_log ~ 연면적m2_log + 공시지가_log + 평균주말매출금액_log + usage_area_log + 승객수점수_log + 본번별평균사용량_log', seoul_ua2_log)

# 모형 적합
res = model.fit()

# 분석 결과 확인
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            rent_ua_log   R-squared:                       0.346
Model:                            OLS   Adj. R-squared:                  0.346
Method:                 Least Squares   F-statistic:                     394.6
Date:                Fri, 16 Oct 2020   Prob (F-statistic):               0.00
Time:                        13:26:12   Log-Likelihood:                -5396.9
No. Observations:                4474   AIC:                         1.081e+04
Df Residuals:                    4467   BIC:                         1.085e+04
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept       4.836e-16      0.012      4e-14      1.000      -0.024       0.024
연면적m2_log         -0.0878      0.013     -6.573      0.000      -0.114      -0.062
공시지가_log           0.4551      0.014     33.622      0.000       0.429       0.482
평균주말매출금액_log       0.0698      0.013      5.251      0.000       0.044       0.096
usage_area_log    -0.1856      0.013    -14.542      0.000      -0.211      -0.161
승객수점수_log          0.1375      0.014     10.124      0.000       0.111       0.164
본번별평균사용량_log       0.1414      0.014     10.442      0.000       0.115       0.168
==============================================================================
Omnibus:                      180.474   Durbin-Watson:                   1.847
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              415.268
Skew:                          -0.238   Prob(JB):                     6.69e-91
Kurtosis:                       4.415   Cond. No.                         1.91
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [24]:
# 한번에 모든 컬럼의 VIF를 계산

pd.DataFrame({'컬럼': column, 'VIF': variance_inflation_factor(model.exog, i)} 
             for i, column in enumerate(model.exog_names)
             if column != 'Intercept')  # 절편의 VIF는 구하지 않는다.

               컬럼       VIF
0       연면적m2_log  1.219530
1        공시지가_log  1.252442
2    평균주말매출금액_log  1.207785
3  usage_area_log  1.113020
4       승객수점수_log  1.261153
5    본번별평균사용량_log  1.253303

In [25]:
# 모형 만들기(연면적m2, usage_area, 공시지가, 매출)
model = ols('rent_ua_log ~ 연면적m2_log + 공시지가_log + 평균주말매출금액_log + usage_area_log', seoul_ua2_log)

# 모형 적합
res = model.fit()

# 분석 결과 확인
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            rent_ua_log   R-squared:                       0.313
Model:                            OLS   Adj. R-squared:                  0.312
Method:                 Least Squares   F-statistic:                     509.2
Date:                Fri, 16 Oct 2020   Prob (F-statistic):               0.00
Time:                        13:26:12   Log-Likelihood:                -5508.3
No. Observations:                4474   AIC:                         1.103e+04
Df Residuals:                    4469   BIC:                         1.106e+04
Df Model:                           4
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept       4.836e-16      0.012    3.9e-14      1.000      -0.024       0.024
연면적m2_log         -0.0534      0.013     -4.146      0.000      -0.079      -0.028
공시지가_log           0.5172      0.013     39.129      0.000       0.491       0.543
평균주말매출금액_log       0.1221      0.013      9.358      0.000       0.097       0.148
usage_area_log    -0.1634      0.013    -12.669      0.000      -0.189      -0.138
==============================================================================
Omnibus:                      180.793   Durbin-Watson:                   1.819
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              448.963
Skew:                          -0.207   Prob(JB):                     3.23e-98
Kurtosis:                       4.496   Cond. No.                         1.51
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [26]:
# 한번에 모든 컬럼의 VIF를 계산

pd.DataFrame({'컬럼': column, 'VIF': variance_inflation_factor(model.exog, i)} 
             for i, column in enumerate(model.exog_names)
             if column != 'Intercept')  # 절편의 VIF는 구하지 않는다.

               컬럼       VIF
0       연면적m2_log  1.079724
1        공시지가_log  1.136566
2    평균주말매출금액_log  1.107754
3  usage_area_log  1.082253

In [27]:
seoul_ua2_log.to_csv("C:/data/now_used/seoul_ua2_log.csv", index = False)